/* now_export_meson.c — Meson exporter */
#include "now_export.h"
#include "now_export_common.h"
#include "now_pom.h"
#include "now_fs.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static const char *meson_opt_level(const char *opt) {
    if (!opt) return "0";
    if (strcmp(opt, "none") == 0)  return "0";
    if (strcmp(opt, "debug") == 0) return "g";
    if (strcmp(opt, "size") == 0)  return "s";
    if (strcmp(opt, "speed") == 0) return "2";
    if (strcmp(opt, "lto") == 0)   return "2";
    return "0";
}

/* Map now C std to meson c_std */
static const char *meson_c_std(const char *std_str) {
    if (!std_str) return "c11";
    if (strcmp(std_str, "c89") == 0 || strcmp(std_str, "c90") == 0) return "c89";
    if (strcmp(std_str, "c99") == 0) return "c99";
    if (strcmp(std_str, "c11") == 0) return "c11";
    if (strcmp(std_str, "c17") == 0 || strcmp(std_str, "c18") == 0) return "c17";
    if (strcmp(std_str, "c23") == 0) return "c2x";
    return "c11";
}

/* Map now C++ std to meson cpp_std */
static const char *meson_cxx_std(const char *std_str) {
    if (!std_str) return "c++17";
    if (strcmp(std_str, "c++11") == 0) return "c++11";
    if (strcmp(std_str, "c++14") == 0) return "c++14";
    if (strcmp(std_str, "c++17") == 0) return "c++17";
    if (strcmp(std_str, "c++20") == 0) return "c++20";
    if (strcmp(std_str, "c++23") == 0) return "c++23";
    return "c++17";
}
NOW_API int now_export_meson(const NowProject *project, const char *basedir,
                               const char *outpath, NowResult *result) {
    if (!project || !outpath) {
        if (result) {
            result->code = NOW_ERR_SCHEMA;
            snprintf(result->message, sizeof(result->message),
                     "export:meson: project and outpath required");
        }
        return -1;
    }

    FILE *fp = fopen(outpath, "w");
    if (!fp) {
        if (result) {
            result->code = NOW_ERR_IO;
            snprintf(result->message, sizeof(result->message),
                     "export:meson: cannot open %s", outpath);
        }
        return -1;
    }

    const char *pname = project->artifact ? project->artifact : "myproject";
    const char *pver  = project->version  ? project->version  : "0.1.0";
    int cxx = export_has_cxx(project);
    const char *lang = cxx ? "cpp" : "c";
    const char *out_type = project->output.type ? project->output.type : "executable";

    /* ---- project() ---- */
    fprintf(fp, "# Generated by now export:meson — do not edit\n\n");
    fprintf(fp, "project('%s', '%s',\n", pname, cxx ? "cpp" : "c");
    fprintf(fp, "  version : '%s',\n", pver);
    if (project->license)
        fprintf(fp, "  license : '%s',\n", project->license);
    fprintf(fp, "  default_options : [\n");
    if (cxx)
        fprintf(fp, "    '%s_std=%s',\n", lang, meson_cxx_std(project->std));
    else
        fprintf(fp, "    '%s_std=%s',\n", lang, meson_c_std(project->std));
    fprintf(fp, "    'optimization=%s',\n", meson_opt_level(
                project->compile.opt ? project->compile.opt : NULL));
    if (project->compile.opt && strcmp(project->compile.opt, "lto") == 0)
        fprintf(fp, "    'b_lto=true',\n");
    fprintf(fp, "  ]\n");
    fprintf(fp, ")\n\n");

    /* ---- Sources ---- */
    const char *src_dir = project->sources.dir ? project->sources.dir : "src/main/c";
    const char *hdr_dir = project->sources.headers ? project->sources.headers : "src/main/h";

    /* Collect source patterns */
    fprintf(fp, "src = files(\n");
    fprintf(fp, "  run_command('find', '%s', '-name', '*.c'", src_dir);
    if (cxx)
        fprintf(fp, ", '-o', '-name', '*.cpp', '-o', '-name', '*.cxx', '-o', '-name', '*.cc'");
    fprintf(fp, ",\n    check : true).stdout().strip().split('\\n'),\n");
    fprintf(fp, ")\n\n");

    /* ---- Include directories ---- */
    fprintf(fp, "inc = include_directories('%s'", hdr_dir);
    if (project->sources.private_headers)
        fprintf(fp, ", '%s'", project->sources.private_headers);
    for (size_t i = 0; i < project->compile.includes.count; i++)
        fprintf(fp, ", '%s'", project->compile.includes.items[i]);
    fprintf(fp, ")\n\n");

    /* ---- Compile args ---- */
    int has_args = (project->compile.warnings.count > 0 ||
                    project->compile.defines.count > 0 ||
                    project->compile.flags.count > 0);
    if (has_args) {
        fprintf(fp, "%s_args = [\n", lang);
        for (size_t i = 0; i < project->compile.warnings.count; i++)
            fprintf(fp, "  '-%s',\n", project->compile.warnings.items[i]);
        for (size_t i = 0; i < project->compile.defines.count; i++)
            fprintf(fp, "  '-D%s',\n", project->compile.defines.items[i]);
        for (size_t i = 0; i < project->compile.flags.count; i++)
            fprintf(fp, "  '%s',\n", project->compile.flags.items[i]);
        fprintf(fp, "]\n\n");
    }

    /* ---- Link args ---- */
    int has_link = (project->link.flags.count > 0 || project->link.libs.count > 0 ||
                    project->link.libdirs.count > 0);
    if (has_link) {
        fprintf(fp, "link_args = [\n");
        for (size_t i = 0; i < project->link.flags.count; i++)
            fprintf(fp, "  '%s',\n", project->link.flags.items[i]);
        for (size_t i = 0; i < project->link.libdirs.count; i++)
            fprintf(fp, "  '-L%s',\n", project->link.libdirs.items[i]);
        for (size_t i = 0; i < project->link.libs.count; i++)
            fprintf(fp, "  '-l%s',\n", project->link.libs.items[i]);
        fprintf(fp, "]\n\n");
    }

    /* ---- Target ---- */
    const char *out_name = project->output.name ? project->output.name : pname;

    if (strcmp(out_type, "executable") == 0) {
        fprintf(fp, "%s = executable('%s', src,\n", out_name, out_name);
    } else if (strcmp(out_type, "static") == 0) {
        fprintf(fp, "%s = static_library('%s', src,\n", out_name, out_name);
    } else if (strcmp(out_type, "shared") == 0) {
        fprintf(fp, "%s = shared_library('%s', src,\n", out_name, out_name);
    } else if (strcmp(out_type, "header-only") == 0) {
        /* Header-only: declare_dependency with include dirs only */
        fprintf(fp, "%s_dep = declare_dependency(\n", out_name);
        fprintf(fp, "  include_directories : inc,\n");
        fprintf(fp, ")\n\n");
        goto meson_deps_comment;
    } else {
        fprintf(fp, "%s = executable('%s', src,\n", out_name, out_name);
    }

    fprintf(fp, "  include_directories : inc,\n");
    if (has_args)
        fprintf(fp, "  %s_args : %s_args,\n", lang, lang);
    if (has_link)
        fprintf(fp, "  link_args : link_args,\n");
    fprintf(fp, "  install : true,\n");
    fprintf(fp, ")\n\n");

meson_deps_comment:
    /* ---- Dependencies comment ---- */
    if (project->deps.count > 0) {
        fprintf(fp, "# Dependencies (add via dependency() or subproject()):\n");
        for (size_t i = 0; i < project->deps.count; i++) {
            const char *scope = project->deps.items[i].scope
                                ? project->deps.items[i].scope : "compile";
            fprintf(fp, "#   %s [%s]\n", project->deps.items[i].id, scope);
        }
        fprintf(fp, "\n");
    }

    /* ---- Test target ---- */
    if (strcmp(out_type, "header-only") != 0) {
        const char *test_dir = project->tests.dir ? project->tests.dir : "src/test/c";
        fprintf(fp, "# Tests\n");
        fprintf(fp, "test_src = files(\n");
        fprintf(fp, "  run_command('find', '%s', '-name', '*.c'", test_dir);
        if (cxx)
            fprintf(fp, ", '-o', '-name', '*.cpp'");
        fprintf(fp, ",\n    check : true).stdout().strip().split('\\n'),\n");
        fprintf(fp, ")\n\n");

        if (strcmp(out_type, "executable") == 0) {
            fprintf(fp, "test_exe = executable('%s_test', test_src,\n", pname);
            fprintf(fp, "  include_directories : inc,\n");
            if (has_args)
                fprintf(fp, "  %s_args : %s_args,\n", lang, lang);
            fprintf(fp, ")\n");
        } else {
            fprintf(fp, "test_exe = executable('%s_test', test_src,\n", pname);
            fprintf(fp, "  include_directories : inc,\n");
            fprintf(fp, "  link_with : %s,\n", out_name);
            if (has_args)
                fprintf(fp, "  %s_args : %s_args,\n", lang, lang);
            fprintf(fp, ")\n");
        }
        fprintf(fp, "test('%s_test', test_exe)\n\n", pname);

        /* ---- Install headers ---- */
        fprintf(fp, "install_subdir('%s', install_dir : "
                    "get_option('includedir'))\n", hdr_dir);
    }

    fclose(fp);

    if (result) {
        result->code = NOW_OK;
        snprintf(result->message, sizeof(result->message),
                 "wrote %s", outpath);
    }
    return 0;
}

/* ---- export:bazel ---- */

