/* now_export_bazel.c — Bazel exporter */
#include "now_export.h"
#include "now_export_common.h"
#include "now_pom.h"
#include "now_fs.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

NOW_API int now_export_bazel(const NowProject *project, const char *basedir,
                               const char *outpath, NowResult *result) {
    if (!project || !outpath) {
        if (result) {
            result->code = NOW_ERR_SCHEMA;
            snprintf(result->message, sizeof(result->message),
                     "export:bazel: project and outpath required");
        }
        return -1;
    }

    FILE *fp = fopen(outpath, "w");
    if (!fp) {
        if (result) {
            result->code = NOW_ERR_IO;
            snprintf(result->message, sizeof(result->message),
                     "export:bazel: cannot open %s", outpath);
        }
        return -1;
    }

    const char *pname = project->artifact ? project->artifact : "myproject";
    int cxx = export_has_cxx(project);
    const char *out_type = project->output.type ? project->output.type : "executable";
    const char *out_name = project->output.name ? project->output.name : pname;
    const char *src_dir = project->sources.dir ? project->sources.dir : "src/main/c";
    const char *hdr_dir = project->sources.headers ? project->sources.headers : "src/main/h";
    const char *test_dir = project->tests.dir ? project->tests.dir : "src/test/c";

    /* ---- Header ---- */
    fprintf(fp, "# Generated by now export:bazel — do not edit\n\n");
    fprintf(fp, "load(\"@rules_cc//cc:defs.bzl\", \"cc_binary\", \"cc_library\", \"cc_test\")\n\n");
    fprintf(fp, "package(default_visibility = [\"//visibility:public\"])\n\n");

    /* ---- COPTS ---- */
    int has_copts = (project->compile.warnings.count > 0 ||
                     project->compile.defines.count > 0 ||
                     project->compile.flags.count > 0 ||
                     project->std != NULL ||
                     (project->compile.opt && strcmp(project->compile.opt, "none") != 0));
    if (has_copts) {
        fprintf(fp, "COPTS = [\n");
        /* Standard */
        if (project->std) {
            fprintf(fp, "    \"-std=%s\",\n", project->std);
        }
        /* Optimization */
        if (project->compile.opt) {
            const char *oflag = export_opt_flags(project->compile.opt);
            if (oflag)
                fprintf(fp, "    \"%s\",\n", oflag);
        }
        for (size_t i = 0; i < project->compile.warnings.count; i++)
            fprintf(fp, "    \"-%s\",\n", project->compile.warnings.items[i]);
        for (size_t i = 0; i < project->compile.defines.count; i++)
            fprintf(fp, "    \"-D%s\",\n", project->compile.defines.items[i]);
        for (size_t i = 0; i < project->compile.flags.count; i++)
            fprintf(fp, "    \"%s\",\n", project->compile.flags.items[i]);
        fprintf(fp, "]\n\n");
    }

    /* ---- LINKOPTS ---- */
    int has_linkopts = (project->link.flags.count > 0 || project->link.libs.count > 0 ||
                        project->link.libdirs.count > 0);
    if (has_linkopts) {
        fprintf(fp, "LINKOPTS = [\n");
        for (size_t i = 0; i < project->link.flags.count; i++)
            fprintf(fp, "    \"%s\",\n", project->link.flags.items[i]);
        for (size_t i = 0; i < project->link.libdirs.count; i++)
            fprintf(fp, "    \"-L%s\",\n", project->link.libdirs.items[i]);
        for (size_t i = 0; i < project->link.libs.count; i++)
            fprintf(fp, "    \"-l%s\",\n", project->link.libs.items[i]);
        fprintf(fp, "]\n\n");
    }

    /* ---- Main target ---- */
    if (strcmp(out_type, "executable") == 0) {
        fprintf(fp, "cc_binary(\n");
        fprintf(fp, "    name = \"%s\",\n", out_name);
    } else if (strcmp(out_type, "header-only") == 0) {
        fprintf(fp, "cc_library(\n");
        fprintf(fp, "    name = \"%s\",\n", out_name);
    } else {
        /* static or shared → cc_library */
        fprintf(fp, "cc_library(\n");
        fprintf(fp, "    name = \"%s\",\n", out_name);
    }

    /* srcs */
    if (strcmp(out_type, "header-only") != 0) {
        fprintf(fp, "    srcs = glob([\"%s/**/*.c\"", src_dir);
        if (cxx)
            fprintf(fp, ", \"%s/**/*.cpp\", \"%s/**/*.cc\", \"%s/**/*.cxx\"",
                    src_dir, src_dir, src_dir);
        fprintf(fp, "]),\n");
    }

    /* hdrs */
    fprintf(fp, "    hdrs = glob([\"%s/**/*.h\"", hdr_dir);
    if (cxx)
        fprintf(fp, ", \"%s/**/*.hpp\"", hdr_dir);
    fprintf(fp, "]),\n");

    /* includes + strip_include_prefix */
    fprintf(fp, "    includes = [\"%s\"],\n", hdr_dir);
    fprintf(fp, "    strip_include_prefix = \"%s\",\n", hdr_dir);

    /* copts + linkopts */
    if (has_copts)
        fprintf(fp, "    copts = COPTS,\n");
    if (has_linkopts && strcmp(out_type, "header-only") != 0)
        fprintf(fp, "    linkopts = LINKOPTS,\n");

    /* linkstatic for static libs */
    if (strcmp(out_type, "static") == 0)
        fprintf(fp, "    linkstatic = True,\n");

    fprintf(fp, ")\n\n");

    /* ---- Dependencies comment ---- */
    if (project->deps.count > 0) {
        fprintf(fp, "# Dependencies (add via deps attribute):\n");
        for (size_t i = 0; i < project->deps.count; i++) {
            const char *scope = project->deps.items[i].scope
                                ? project->deps.items[i].scope : "compile";
            fprintf(fp, "#   %s [%s]\n", project->deps.items[i].id, scope);
        }
        fprintf(fp, "\n");
    }

    /* ---- Test target ---- */
    fprintf(fp, "cc_test(\n");
    fprintf(fp, "    name = \"%s_test\",\n", pname);
    fprintf(fp, "    srcs = glob([\"%s/**/*.c\"", test_dir);
    if (cxx)
        fprintf(fp, ", \"%s/**/*.cpp\"", test_dir);
    fprintf(fp, "]),\n");
    if (strcmp(out_type, "executable") == 0) {
        /* For executables, compile test with the source files */
        fprintf(fp, "    hdrs = glob([\"%s/**/*.h\"", hdr_dir);
        if (cxx)
            fprintf(fp, ", \"%s/**/*.hpp\"", hdr_dir);
        fprintf(fp, "]),\n");
        fprintf(fp, "    includes = [\"%s\"],\n", hdr_dir);
    } else {
        fprintf(fp, "    deps = [\":%s\"],\n", out_name);
    }
    if (has_copts)
        fprintf(fp, "    copts = COPTS,\n");
    fprintf(fp, ")\n");

    fclose(fp);

    if (result) {
        result->code = NOW_OK;
        snprintf(result->message, sizeof(result->message),
                 "wrote %s", outpath);
    }
    return 0;
}
