/*
 * main.c — now CLI entry point
 *
 * Usage:
 *   now build          procure → build → link
 *   now compile        procure → compile only
 *   now link           link only (no rebuild)
 *   now test           procure → build → link → test
 *   now procure        dependency resolution only
 *   now publish        package → publish to registry
 *   now clean          delete target/
 *   now version        print version
 */

#include "now_pom.h"
#include "now.h"
#include "now_build.h"
#include "now_fs.h"
#include "now_procure.h"
#include "now_package.h"
#include "now_plugin.h"
#include "now_ci.h"
#include "now_workspace.h"
#include "now_arch.h"
#include "now_layer.h"
#include "now_export.h"
#include "now_trust.h"
#include "now_repro.h"
#include "now_advisory.h"
#include "now_cache.h"
#include "pasta.h"
#include "alforno.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#ifdef _WIN32
  #include <direct.h>
  #define getcwd_compat _getcwd
#else
  #include <unistd.h>
  #define getcwd_compat getcwd
#endif

/* ---- Alforno-based project templates for `now init` ---- */

/* Template pastlet: project descriptor with {variable} placeholders.
   @vars provides defaults; the CLI overrides them via a second input. */
static const char NOW_INIT_TEMPLATE[] =
    "@vars {\n"
    "  group:    \"com.example\",\n"
    "  artifact: \"myproject\",\n"
    "  version:  \"0.1.0\",\n"
    "  lang:     \"c\",\n"
    "  std:      \"c11\",\n"
    "  type:     \"executable\"\n"
    "}\n"
    "@project {\n"
    "  group:    \"{group}\",\n"
    "  artifact: \"{artifact}\",\n"
    "  version:  \"{version}\",\n"
    "  langs:    [\"{lang}\"],\n"
    "  std:      \"{std}\",\n"
    "  output:   { type: \"{type}\", name: \"{artifact}\" },\n"
    "  compile:  { warnings: [\"Wall\", \"Wextra\"] },\n"
    "  deps:     []\n"
    "}\n";

/*
 * Render a now.pasta project descriptor using alforno templates.
 *
 * The template contains {variable} placeholders. CLI arguments are passed
 * as a @vars override pastlet that merges with (and overrides) the template
 * defaults. Alforno's Pass 1 (parameterize) resolves all variables.
 *
 * Returns a malloc'd string (Pasta-formatted), or NULL on error.
 */
static char *now_init_render(const char *group, const char *artifact,
                              const char *version, const char *lang,
                              const char *std_str, const char *type) {
    AlfResult ar;
    AlfContext *ctx = alf_create(ALF_AGGREGATE, &ar);
    if (!ctx) return NULL;

    /* Input 1: template with defaults */
    if (alf_add_input(ctx, NOW_INIT_TEMPLATE, strlen(NOW_INIT_TEMPLATE), &ar) != 0) {
        alf_free(ctx);
        return NULL;
    }

    /* Input 2: CLI overrides as @vars (last-write-wins merges with template @vars) */
    char vars[512];
    snprintf(vars, sizeof(vars),
        "@vars {\n"
        "  group:    \"%s\",\n"
        "  artifact: \"%s\",\n"
        "  version:  \"%s\",\n"
        "  lang:     \"%s\",\n"
        "  std:      \"%s\",\n"
        "  type:     \"%s\"\n"
        "}\n",
        group, artifact, version, lang, std_str, type);

    if (alf_add_input(ctx, vars, strlen(vars), &ar) != 0) {
        alf_free(ctx);
        return NULL;
    }

    /* Process: parameterize (resolve {vars}), merge, link */
    PastaValue *output = alf_process(ctx, &ar);
    alf_free(ctx);
    if (!output) return NULL;

    /* Extract the @project section and serialize it as a standalone file.
       Comment header is prepended manually. */
    const PastaValue *proj = pasta_map_get(output, "project");
    if (!proj) {
        pasta_free(output);
        return NULL;
    }

    char *body = pasta_write(proj, PASTA_PRETTY);
    pasta_free(output);
    if (!body) return NULL;

    /* Prepend a comment header */
    size_t hdr_len = 128 + strlen(lang);
    size_t total = hdr_len + strlen(body) + 1;
    char *result = (char *)malloc(total);
    if (!result) { free(body); return NULL; }

    int pos = snprintf(result, total,
        "; Generated by: now init %s\n"
        "; Edit this file to configure your project.\n",
        lang);
    strcat(result + pos, body);
    free(body);
    return result;
}

static void usage(void) {
    fprintf(stderr,
        "now %s — native build tool for C/C++\n\n"
        "Usage: now <phase> [options]\n\n"
        "Phases:\n"
        "  build      Procure deps, generate, compile sources, link output\n"
        "  compile    Procure deps, generate, compile only (no link)\n"
        "  generate   Run generate-phase plugins only\n"
        "  link       Link only (no compile)\n"
        "  test       Build and run tests\n"
        "  procure    Resolve and download dependencies\n"
        "  package    Assemble distributable archive in target/pkg/\n"
        "  install    Install to local repo (~/.now/repo/)\n"
        "  init       Scaffold a new project: init [lang] [--group G] [--artifact A]\n"
        "  fmt        Format .pasta files: fmt [file...] [--sorted]\n"
        "  publish    Upload package to remote registry\n"
        "  yank       Yank a published version: yank <g:a:v> --repo URL\n"
        "  compile-db   Generate compile_commands.json for IDE/LSP\n"
        "  dep:updates  Check dependencies for newer versions\n"
        "  cache:clean  Remove all cached build objects\n"
        "  cache:stats  Show build cache statistics\n"
        "  cache:mirror Mirror artifacts from registry to local cache\n"
        "  export:cmake  Generate CMakeLists.txt from now.pasta\n"
        "  export:make   Generate Makefile from now.pasta\n"
        "  export:meson  Generate meson.build from now.pasta\n"
        "  export:bazel  Generate BUILD.bazel from now.pasta\n"
        "  export:maven  Generate pom.xml from now.pasta\n"
        "  import:maven  Convert pom.xml to now.pasta\n"
        "  layers:show  Show layer stack and effective configuration\n"
        "  trust:list   List trusted keys\n"
        "  trust:add    Add key: trust:add <scope> <key> [comment]\n"
        "  verify       Verify archive signature\n"
        "  reproducible:check  Build twice and compare output hashes\n"
        "  advisory:check      Check deps against advisory database\n"
        "  advisory:update     Fetch latest advisory database\n"
        "  layers:audit Report advisory lock violations\n"
        "  ci         Build, test, report (CI mode with structured output)\n"
        "  clean      Delete target/ directory\n"
        "  version    Print version and exit\n\n"
        "Options:\n"
        "  -v              Verbose output\n"
        "  -j N            Parallel jobs (default: CPU count)\n"
        "  --output FMT    Output format: text, json, pasta\n"
        "  --locked        Fail if lock file is inconsistent\n"
        "  --offline       No network access\n"
        "  --target TRIPLE Target platform triple (os:arch:variant)\n"
        "  --no-color      Disable ANSI colors\n"
        "  -h              Show this help\n",
        now_version());
}

/* Recursively delete a directory tree */
static int rmdir_recursive(const char *path) {
#ifdef _WIN32
    char cmd[1024];
    snprintf(cmd, sizeof(cmd), "rmdir /s /q \"%s\"", path);
    return system(cmd);
#else
    char cmd[1024];
    snprintf(cmd, sizeof(cmd), "rm -rf '%s'", path);
    return system(cmd);
#endif
}

int main(int argc, char *argv[]) {
    if (argc < 2) {
        usage();
        return 1;
    }

    const char *phase = argv[1];
    int verbose = 0;
    int jobs = 0;  /* 0 = auto (CPU count) */
    const char *repo_url = NULL;
    const char *output_fmt = NULL;
    int flag_locked = 0;
    int flag_offline = 0;
    int flag_no_color = 0;
    const char *target_str = NULL;

    /* Check for flags in remaining args */
    for (int i = 2; i < argc; i++) {
        if (strcmp(argv[i], "-v") == 0 || strcmp(argv[i], "--verbose") == 0)
            verbose = 1;
        else if (strcmp(argv[i], "-h") == 0 || strcmp(argv[i], "--help") == 0) {
            usage();
            return 0;
        }
        else if (strcmp(argv[i], "--repo") == 0 && i + 1 < argc)
            repo_url = argv[++i];
        else if (strcmp(argv[i], "--output") == 0 && i + 1 < argc)
            output_fmt = argv[++i];
        else if (strcmp(argv[i], "--locked") == 0)
            flag_locked = 1;
        else if (strcmp(argv[i], "--offline") == 0)
            flag_offline = 1;
        else if (strcmp(argv[i], "--no-color") == 0)
            flag_no_color = 1;
        else if (strcmp(argv[i], "--target") == 0 && i + 1 < argc)
            target_str = argv[++i];
        else if (strcmp(argv[i], "-j") == 0 && i + 1 < argc) {
            jobs = atoi(argv[++i]);
            if (jobs < 1) jobs = 1;
        }
        else if (strncmp(argv[i], "-j", 2) == 0 && argv[i][2] >= '1' && argv[i][2] <= '9') {
            jobs = atoi(argv[i] + 2);
            if (jobs < 1) jobs = 1;
        }
    }

    /* Handle version and help */
    if (strcmp(phase, "version") == 0 || strcmp(phase, "--version") == 0) {
        printf("now %s\n", now_version());
        return 0;
    }
    if (strcmp(phase, "-h") == 0 || strcmp(phase, "--help") == 0
        || strcmp(phase, "help") == 0) {
        usage();
        return 0;
    }

    /* Handle clean */
    if (strcmp(phase, "clean") == 0) {
        char cwd[512];
        if (!getcwd_compat(cwd, sizeof(cwd))) {
            fprintf(stderr, "error: cannot determine working directory\n");
            return 1;
        }
        char *target = now_path_join(cwd, "target");
        if (target && now_path_exists(target)) {
            if (verbose) fprintf(stderr, "cleaning %s\n", target);
            rmdir_recursive(target);
        }
        free(target);
        return 0;
    }

    /* ---- now fmt ---- */
    if (strcmp(phase, "fmt") == 0) {
        /* Format one or more .pasta files in-place */
        int fmt_count = 0;
        int fmt_flags = PASTA_PRETTY;
        int sorted = 0;

        /* Collect file arguments and flags */
        const char *files[64];
        int nfiles = 0;
        for (int i = 2; i < argc && nfiles < 64; i++) {
            if (strcmp(argv[i], "--sorted") == 0)
                sorted = 1;
            else if (argv[i][0] != '-')
                files[nfiles++] = argv[i];
        }
        if (sorted) fmt_flags |= PASTA_SORTED;

        /* Default: format now.pasta in current directory */
        char cwd_buf[512];
        char *default_file = NULL;
        if (nfiles == 0) {
            if (getcwd_compat(cwd_buf, sizeof(cwd_buf))) {
                default_file = now_path_join(cwd_buf, "now.pasta");
                if (default_file && now_path_exists(default_file)) {
                    files[0] = default_file;
                    nfiles = 1;
                } else {
                    fprintf(stderr, "error: no now.pasta found\n");
                    free(default_file);
                    return 1;
                }
            }
        }

        for (int i = 0; i < nfiles; i++) {
            /* Read file */
            FILE *f = fopen(files[i], "rb");
            if (!f) {
                fprintf(stderr, "error: cannot open %s\n", files[i]);
                continue;
            }
            fseek(f, 0, SEEK_END);
            long flen = ftell(f);
            fseek(f, 0, SEEK_SET);
            char *content = malloc((size_t)flen + 1);
            if (!content) { fclose(f); continue; }
            fread(content, 1, (size_t)flen, f);
            content[flen] = '\0';
            fclose(f);

            /* Parse */
            PastaResult pr;
            PastaValue *val = pasta_parse(content, (size_t)flen, &pr);
            free(content);
            if (!val) {
                fprintf(stderr, "%s:%d:%d: %s\n",
                        files[i], pr.line, pr.col, pr.message);
                continue;
            }

            /* Write back formatted */
            int write_flags = fmt_flags;
            if (pr.sections) write_flags |= PASTA_SECTIONS;
            char *formatted = pasta_write(val, write_flags);
            pasta_free(val);
            if (!formatted) {
                fprintf(stderr, "error: failed to format %s\n", files[i]);
                continue;
            }

            f = fopen(files[i], "w");
            if (f) {
                fputs(formatted, f);
                fclose(f);
                fmt_count++;
                if (verbose) printf("  formatted %s\n", files[i]);
            }
            free(formatted);
        }

        free(default_file);
        printf("formatted %d file(s)\n", fmt_count);
        return 0;
    }

    /* ---- now init / now sketch ---- */
    if (strcmp(phase, "init") == 0 || strcmp(phase, "sketch") == 0) {
        char cwd[512];
        if (!getcwd_compat(cwd, sizeof(cwd))) {
            fprintf(stderr, "error: cannot determine working directory\n");
            return 1;
        }

        /* Parse init-specific flags */
        const char *lang  = "c";
        const char *group = "com.example";
        const char *art   = NULL;
        const char *type  = "executable";
        for (int i = 2; i < argc; i++) {
            if (strcmp(argv[i], "--lang") == 0 && i + 1 < argc)
                lang = argv[++i];
            else if (strcmp(argv[i], "--group") == 0 && i + 1 < argc)
                group = argv[++i];
            else if (strcmp(argv[i], "--artifact") == 0 && i + 1 < argc)
                art = argv[++i];
            else if (strcmp(argv[i], "--type") == 0 && i + 1 < argc)
                type = argv[++i];
            else if (argv[i][0] != '-')
                lang = argv[i];  /* positional: language */
        }

        /* Derive artifact from directory name if not specified */
        char art_buf[128];
        if (!art) {
            const char *dir_name = strrchr(cwd, '/');
            if (!dir_name) dir_name = strrchr(cwd, '\\');
            if (dir_name) dir_name++;
            else dir_name = "myproject";
            strncpy(art_buf, dir_name, sizeof(art_buf) - 1);
            art_buf[sizeof(art_buf) - 1] = '\0';
            /* Sanitize: lowercase, replace spaces/dots with hyphens */
            for (char *p = art_buf; *p; p++) {
                if (*p >= 'A' && *p <= 'Z') *p += 32;
                if (*p == ' ' || *p == '.') *p = '-';
            }
            art = art_buf;
        }

        /* Determine source directories based on language */
        const char *src_dir = "src/main/c";
        const char *hdr_dir = "src/main/h";
        const char *tst_dir = "src/test/c";
        const char *src_ext = ".c";
        const char *std_str = "c11";
        if (strcmp(lang, "c++") == 0 || strcmp(lang, "cpp") == 0) {
            src_dir = "src/main/cpp";
            hdr_dir = "src/main/h";
            tst_dir = "src/test/cpp";
            src_ext = ".cpp";
            std_str = "c++17";
            lang = "c++";
        }

        /* Check if now.pasta already exists */
        char *pasta_path = now_path_join(cwd, "now.pasta");
        if (now_path_exists(pasta_path)) {
            fprintf(stderr, "now.pasta already exists — skipping\n");
        } else {
            /* Render now.pasta via alforno template */
            char *content = now_init_render(group, art, "0.1.0",
                                             lang, std_str, type);
            if (!content) {
                fprintf(stderr, "error: template rendering failed\n");
                free(pasta_path);
                return 1;
            }
            FILE *f = fopen(pasta_path, "w");
            if (!f) {
                fprintf(stderr, "error: cannot write %s\n", pasta_path);
                free(content);
                free(pasta_path);
                return 1;
            }
            fputs(content, f);
            fclose(f);
            free(content);
            printf("  created now.pasta\n");
        }
        free(pasta_path);

        /* Create directories */
        char *dirs[] = { NULL, NULL, NULL, NULL };
        dirs[0] = now_path_join(cwd, src_dir);
        dirs[1] = now_path_join(cwd, hdr_dir);
        dirs[2] = now_path_join(cwd, tst_dir);
        for (int i = 0; dirs[i]; i++) {
            if (!now_path_exists(dirs[i])) {
                now_mkdir_p(dirs[i]);
                printf("  created %s/\n", dirs[i] + strlen(cwd) + 1);
            }
            free(dirs[i]);
        }

        /* Write placeholder main source if empty */
        char main_name[64];
        snprintf(main_name, sizeof(main_name), "main%s", src_ext);
        char *main_rel = now_path_join(src_dir, main_name);
        char *main_path = now_path_join(cwd, main_rel);
        if (!now_path_exists(main_path)) {
            FILE *f = fopen(main_path, "w");
            if (f) {
                if (strcmp(lang, "c++") == 0) {
                    fprintf(f,
                        "#include <iostream>\n\n"
                        "int main() {\n"
                        "    std::cout << \"hello from %s\" << std::endl;\n"
                        "    return 0;\n"
                        "}\n", art);
                } else {
                    fprintf(f,
                        "#include <stdio.h>\n\n"
                        "int main(void) {\n"
                        "    printf(\"hello from %s\\n\");\n"
                        "    return 0;\n"
                        "}\n", art);
                }
                fclose(f);
                printf("  created %s\n", main_rel);
            }
        }
        free(main_path);
        free(main_rel);

        /* Write placeholder header */
        char hdr_name[128];
        snprintf(hdr_name, sizeof(hdr_name), "%s.h", art);
        char *hdr_rel = now_path_join(hdr_dir, hdr_name);
        char *hdr_path = now_path_join(cwd, hdr_rel);
        if (!now_path_exists(hdr_path)) {
            FILE *f = fopen(hdr_path, "w");
            if (f) {
                /* Generate include guard from artifact name */
                char guard[128];
                snprintf(guard, sizeof(guard), "%s_H", art);
                for (char *p = guard; *p; p++) {
                    if (*p >= 'a' && *p <= 'z') *p -= 32;
                    if (*p == '-' || *p == '.') *p = '_';
                }
                fprintf(f,
                    "#ifndef %s\n"
                    "#define %s\n\n"
                    "/* %s public API */\n\n"
                    "#endif /* %s */\n",
                    guard, guard, art, guard);
                fclose(f);
                printf("  created %s\n", hdr_rel);
            }
        }
        free(hdr_path);
        free(hdr_rel);

        /* Write placeholder test */
        char tst_name[64];
        snprintf(tst_name, sizeof(tst_name), "main_test%s", src_ext);
        char *tst_rel = now_path_join(tst_dir, tst_name);
        char *tst_path = now_path_join(cwd, tst_rel);
        if (!now_path_exists(tst_path)) {
            FILE *f = fopen(tst_path, "w");
            if (f) {
                if (strcmp(lang, "c++") == 0) {
                    fprintf(f,
                        "#include <cassert>\n\n"
                        "int main() {\n"
                        "    assert(1 == 1);\n"
                        "    return 0;\n"
                        "}\n");
                } else {
                    fprintf(f,
                        "#include <assert.h>\n\n"
                        "int main(void) {\n"
                        "    assert(1 == 1);\n"
                        "    return 0;\n"
                        "}\n");
                }
                fclose(f);
                printf("  created %s\n", tst_rel);
            }
        }
        free(tst_path);
        free(tst_rel);

        /* Write .gitignore if absent */
        char *gi_path = now_path_join(cwd, ".gitignore");
        if (!now_path_exists(gi_path)) {
            FILE *f = fopen(gi_path, "w");
            if (f) {
                fprintf(f, "target/\n");
                fclose(f);
                printf("  created .gitignore\n");
            }
        }
        free(gi_path);

        printf("\nready — run 'now build' to compile\n");
        return 0;
    }

    /* Trust store commands (no project file needed) */
    if (strcmp(phase, "trust:list") == 0) {
        NowTrustStore store;
        now_trust_init(&store);
        NowResult result;
        memset(&result, 0, sizeof(result));
        int rc = now_trust_load(&store, &result);
        if (rc != 0) {
            fprintf(stderr, "error: %s\n", result.message);
            now_trust_free(&store);
            return 1;
        }
        if (store.count == 0) {
            printf("No trusted keys. Use 'now trust:add' to add keys.\n");
        } else {
            printf("Trusted keys (%zu):\n\n", store.count);
            for (size_t i = 0; i < store.count; i++) {
                printf("  [%zu] scope: %-20s key: %.16s...",
                       i, store.keys[i].scope, store.keys[i].key);
                if (store.keys[i].comment)
                    printf("  (%s)", store.keys[i].comment);
                printf("\n");
            }
        }
        now_trust_free(&store);
        return 0;
    }

    if (strcmp(phase, "trust:add") == 0) {
        if (argc < 4) {
            fprintf(stderr, "usage: now trust:add <scope> <key> [comment]\n");
            return 1;
        }
        const char *scope = argv[2];
        const char *key = argv[3];
        const char *comment = (argc > 4) ? argv[4] : NULL;

        NowTrustStore store;
        now_trust_init(&store);
        NowResult result;
        memset(&result, 0, sizeof(result));

        now_trust_load(&store, &result);
        int rc = now_trust_add(&store, scope, key, comment);
        if (rc != 0) {
            fprintf(stderr, "error: failed to add key\n");
            now_trust_free(&store);
            return 1;
        }
        rc = now_trust_save(&store, &result);
        if (rc != 0) {
            fprintf(stderr, "error: %s\n", result.message);
            now_trust_free(&store);
            return 1;
        }
        printf("added key for scope '%s'\n", scope);
        now_trust_free(&store);
        return 0;
    }

    if (strcmp(phase, "yank") == 0) {
        if (argc < 3) {
            fprintf(stderr, "usage: now yank <group:artifact:version> [--repo URL] [--reason \"...\"]\n");
            return 1;
        }
        const char *coord_str = argv[2];
        const char *reason = NULL;
        for (int i = 3; i < argc; i++) {
            if (strcmp(argv[i], "--reason") == 0 && i + 1 < argc)
                reason = argv[++i];
        }

        NowCoordinate coord;
        if (now_coord_parse(coord_str, &coord) != 0) {
            fprintf(stderr, "error: invalid coordinate '%s' (expected group:artifact:version)\n",
                    coord_str);
            return 1;
        }

        if (!repo_url) {
            fprintf(stderr, "error: --repo is required for yank\n");
            now_coord_free(&coord);
            return 1;
        }

        NowResult result;
        memset(&result, 0, sizeof(result));
        int rc = now_publish_yank(repo_url, coord.group, coord.artifact,
                                   coord.version, reason, verbose, &result);
        now_coord_free(&coord);
        if (rc != 0) {
            fprintf(stderr, "error: %s\n", result.message);
            return 1;
        }
        printf("yanked %s\n", coord_str);
        return 0;
    }

    if (strcmp(phase, "cache:clean") == 0) {
        int rc = now_cache_clean();
        if (rc < 0) {
            fprintf(stderr, "error: failed to clean build cache\n");
            return 1;
        }
        if (verbose) fprintf(stderr, "build cache cleaned\n");
        return 0;
    }

    if (strcmp(phase, "cache:stats") == 0) {
        return now_cache_print_stats();
    }

    if (strcmp(phase, "cache:mirror") == 0) {
        if (!repo_url) {
            fprintf(stderr, "error: --repo is required for cache:mirror\n");
            return 1;
        }
        /* Optional: remaining args as coords filter */
        const char *coords = (argc > 2) ? argv[2] : NULL;
        NowResult result;
        memset(&result, 0, sizeof(result));
        int rc = now_cache_mirror(repo_url, coords, verbose, &result);
        if (rc < 0) {
            fprintf(stderr, "error: %s\n", result.message);
            return 1;
        }
        printf("mirrored %d artifacts\n", rc);
        return 0;
    }

    /* All other phases need a project descriptor */
    char cwd[512];
    if (!getcwd_compat(cwd, sizeof(cwd))) {
        fprintf(stderr, "error: cannot determine working directory\n");
        return 1;
    }

    /* import:maven doesn't need an existing now.pasta */
    if (strcmp(phase, "import:maven") == 0) {
        const char *pom_file = "pom.xml";
        for (int a = 2; a < argc - 1; a++) {
            if (strcmp(argv[a], "--file") == 0) {
                pom_file = argv[a + 1];
                break;
            }
        }
        char *pom_path = now_path_join(cwd, pom_file);
        NowResult result;
        memset(&result, 0, sizeof(result));
        if (!pom_path) {
            fprintf(stderr, "error: cannot construct pom.xml path\n");
            return 1;
        }
        NowProject *imported = now_import_maven(pom_path, &result);
        if (!imported) {
            fprintf(stderr, "error: %s\n", result.message);
            free(pom_path);
            return 1;
        }
        char *out = now_path_join(cwd, "now.pasta");
        int rc = 0;
        if (!out) {
            fprintf(stderr, "error: cannot construct output path\n");
            rc = 1;
        } else {
            rc = now_import_maven_write(imported, out, &result);
            if (rc != 0)
                fprintf(stderr, "error: %s\n", result.message);
            else
                printf("imported %s -> %s\n", pom_file, out);
            free(out);
        }
        now_project_free(imported);
        free(pom_path);
        return rc;
    }

    /* Find now.pasta in current directory */
    char *descriptor = now_path_join(cwd, "now.pasta");
    if (!descriptor || !now_path_exists(descriptor)) {
        free(descriptor);
        fprintf(stderr, "error: no now.pasta found in %s\n", cwd);
        return 3;
    }

    NowResult result;
    memset(&result, 0, sizeof(result));

    NowProject *project = now_project_load(descriptor, &result);
    free(descriptor);
    if (!project) {
        fprintf(stderr, "error: %s\n", result.message);
        return 3;
    }

    int rc = 0;

    if (strcmp(phase, "procure") == 0) {
        NowProcureOpts opts = {0};
        rc = now_procure(project, &opts, &result);
        if (rc != 0)
            fprintf(stderr, "error: %s\n", result.message);
        else if (verbose)
            fprintf(stderr, "procure: done\n");

    } else if (strcmp(phase, "dep:updates") == 0) {
        printf("Checking for dependency updates...\n");
        rc = now_dep_updates(project, repo_url, verbose, &result);
        if (rc < 0)
            fprintf(stderr, "error: %s\n", result.message);
        else if (rc == 0)
            printf("all dependencies up to date\n");
        else
            printf("%d update(s) available\n", rc);
        rc = (rc < 0) ? 1 : 0;

    } else if (strcmp(phase, "compile-db") == 0) {
        rc = now_compile_db(project, cwd, &result);
        if (rc < 0)
            fprintf(stderr, "error: %s\n", result.message);
        else
            printf("%s\n", result.message);
        rc = (rc < 0) ? 1 : 0;

    } else if (strcmp(phase, "generate") == 0) {
        NowPluginResult gen;
        now_plugin_result_init(&gen);
        rc = now_plugin_run_hook(project, cwd, NOW_HOOK_GENERATE,
                                  verbose, &gen, &result);
        if (rc != 0)
            fprintf(stderr, "error: %s\n", result.message);
        else if (verbose)
            fprintf(stderr, "generate: %zu source(s) produced\n",
                    gen.sources.count);
        now_plugin_result_free(&gen);

    } else if (strcmp(phase, "build") == 0) {
        if (now_is_workspace(project)) {
            NowWorkspace ws;
            rc = now_workspace_init(&ws, project, cwd, &result);
            if (rc == 0)
                rc = now_workspace_build(&ws, verbose, jobs, &result);
            now_workspace_free(&ws);
        } else {
            rc = now_build(project, cwd, verbose, jobs, &result);
        }
        if (rc != 0)
            fprintf(stderr, "error: %s\n", result.message);

    } else if (strcmp(phase, "compile") == 0) {
        rc = now_compile(project, cwd, verbose, jobs, &result);
        if (rc != 0)
            fprintf(stderr, "error: %s\n", result.message);

    } else if (strcmp(phase, "test") == 0) {
        rc = now_test(project, cwd, verbose, jobs, &result);
        if (rc != 0)
            fprintf(stderr, "error: %s\n", result.message);

    } else if (strcmp(phase, "package") == 0) {
        /* Build first, then package */
        rc = now_build(project, cwd, verbose, jobs, &result);
        if (rc != 0) {
            fprintf(stderr, "error: %s\n", result.message);
        } else {
            rc = now_package(project, cwd, verbose, &result);
            if (rc != 0)
                fprintf(stderr, "error: %s\n", result.message);
        }

    } else if (strcmp(phase, "install") == 0) {
        /* Build first, then install */
        rc = now_build(project, cwd, verbose, jobs, &result);
        if (rc != 0) {
            fprintf(stderr, "error: %s\n", result.message);
        } else {
            rc = now_install(project, cwd, verbose, &result);
            if (rc != 0)
                fprintf(stderr, "error: %s\n", result.message);
        }

    } else if (strcmp(phase, "publish") == 0) {
        /* Build → package → publish */
        rc = now_build(project, cwd, verbose, jobs, &result);
        if (rc != 0) {
            fprintf(stderr, "error: %s\n", result.message);
        } else {
            rc = now_package(project, cwd, verbose, &result);
            if (rc != 0) {
                fprintf(stderr, "error: %s\n", result.message);
            } else {
                rc = now_publish(project, cwd, repo_url, verbose, &result);
                if (rc != 0)
                    fprintf(stderr, "error: %s\n", result.message);
            }
        }

    } else if (strcmp(phase, "export:cmake") == 0) {
        char *out = now_path_join(cwd, "CMakeLists.txt");
        if (!out) {
            fprintf(stderr, "error: cannot construct output path\n");
            rc = 1;
        } else {
            rc = now_export_cmake(project, cwd, out, &result);
            if (rc != 0)
                fprintf(stderr, "error: %s\n", result.message);
            else
                printf("wrote %s\n", out);
            free(out);
        }

    } else if (strcmp(phase, "export:make") == 0) {
        char *out = now_path_join(cwd, "Makefile");
        if (!out) {
            fprintf(stderr, "error: cannot construct output path\n");
            rc = 1;
        } else {
            rc = now_export_make(project, cwd, out, &result);
            if (rc != 0)
                fprintf(stderr, "error: %s\n", result.message);
            else
                printf("wrote %s\n", out);
            free(out);
        }

    } else if (strcmp(phase, "export:meson") == 0) {
        char *out = now_path_join(cwd, "meson.build");
        if (!out) {
            fprintf(stderr, "error: cannot construct output path\n");
            rc = 1;
        } else {
            rc = now_export_meson(project, cwd, out, &result);
            if (rc != 0)
                fprintf(stderr, "error: %s\n", result.message);
            else
                printf("wrote %s\n", out);
            free(out);
        }

    } else if (strcmp(phase, "export:bazel") == 0) {
        char *out = now_path_join(cwd, "BUILD.bazel");
        if (!out) {
            fprintf(stderr, "error: cannot construct output path\n");
            rc = 1;
        } else {
            rc = now_export_bazel(project, cwd, out, &result);
            if (rc != 0)
                fprintf(stderr, "error: %s\n", result.message);
            else
                printf("wrote %s\n", out);
            free(out);
        }

    } else if (strcmp(phase, "export:maven") == 0) {
        char *out = now_path_join(cwd, "pom.xml");
        if (!out) {
            fprintf(stderr, "error: cannot construct output path\n");
            rc = 1;
        } else {
            rc = now_export_maven(project, cwd, out, &result);
            if (rc != 0)
                fprintf(stderr, "error: %s\n", result.message);
            else
                printf("wrote %s\n", out);
            free(out);
        }

    } else if (strcmp(phase, "layers:show") == 0) {
        NowLayerStack stack;
        now_layer_stack_init(&stack);
        now_layer_discover(&stack, cwd, &result);
        now_layer_push_project(&stack, project);

        printf("Layer stack (%zu layers):\n\n", stack.count);
        for (size_t i = 0; i < stack.count; i++) {
            const NowLayer *l = &stack.layers[i];
            printf("  [%zu] %s", i, l->id);
            if (l->path) printf("  (%s)", l->path);
            printf("\n");
            for (size_t j = 0; j < l->section_count; j++) {
                const NowLayerSection *s = &l->sections[j];
                printf("      @%-20s %s",
                       s->name,
                       s->policy == NOW_POLICY_LOCKED ? "locked" : "open");
                if (s->description)
                    printf("  — %s", s->description);
                printf("\n");
            }
        }

        /* Show effective config if --effective */
        for (int i = 2; i < argc; i++) {
            if (strcmp(argv[i], "--effective") == 0) {
                printf("\nEffective configuration:\n");
                const char *section_names[] = {
                    "compile", "repos", "toolchain", "advisory",
                    "private_groups", "link", NULL
                };
                NowAuditReport audit;
                now_audit_init(&audit);
                for (int s = 0; section_names[s]; s++) {
                    PastaValue *eff = (PastaValue *)now_layer_merge_section(
                        &stack, section_names[s], &audit);
                    if (eff && pasta_count(eff) > 0) {
                        char *text = pasta_write(eff, PASTA_PRETTY);
                        if (text) {
                            printf("\n  @%s: %s\n", section_names[s], text);
                            free(text);
                        }
                    }
                    if (eff) pasta_free(eff);
                }
                now_audit_free(&audit);
                break;
            }
        }

        now_layer_stack_free(&stack);

    } else if (strcmp(phase, "layers:audit") == 0) {
        NowLayerStack stack;
        now_layer_stack_init(&stack);
        now_layer_discover(&stack, cwd, &result);
        now_layer_push_project(&stack, project);

        NowAuditReport audit;
        now_audit_init(&audit);

        /* Merge all known sections to collect violations */
        const char *section_names[] = {
            "compile", "repos", "toolchain", "advisory",
            "private_groups", "link", NULL
        };
        for (int i = 0; section_names[i]; i++) {
            PastaValue *eff = (PastaValue *)now_layer_merge_section(
                &stack, section_names[i], &audit);
            if (eff) pasta_free(eff);
        }

        char *report = now_audit_format(&audit);
        if (report) {
            printf("%s", report);
            free(report);
        }

        rc = (audit.count > 0) ? 1 : 0;
        now_audit_free(&audit);
        now_layer_stack_free(&stack);

    } else if (strcmp(phase, "ci") == 0) {
        /* CI lifecycle: build → test with structured output and report */
        NowCIEnv ci_env;
        now_ci_detect(&ci_env);
        if (flag_locked)  ci_env.locked = 1;
        if (flag_offline) ci_env.offline = 1;
        if (flag_no_color) ci_env.no_color = 1;
        if (output_fmt) {
            if (strcmp(output_fmt, "json") == 0)
                ci_env.format = NOW_OUTPUT_JSON;
            else if (strcmp(output_fmt, "pasta") == 0)
                ci_env.format = NOW_OUTPUT_PASTA;
            else if (strcmp(output_fmt, "text") == 0)
                ci_env.format = NOW_OUTPUT_TEXT;
        }
        rc = now_ci_run(project, cwd, &ci_env, jobs, &result);
        if (rc != 0 && ci_env.format == NOW_OUTPUT_TEXT)
            fprintf(stderr, "error: %s\n", result.message);

    } else if (strcmp(phase, "reproducible:check") == 0) {
        NowReproConfig repro_cfg;
        now_repro_from_project(&repro_cfg, project);
        if (!repro_cfg.enabled) {
            fprintf(stderr, "note: reproducible: not set in now.pasta — "
                            "checking anyway\n");
            repro_cfg.enabled = 1;
            if (!repro_cfg.timebase)
                repro_cfg.timebase = strdup("zero");
            repro_cfg.path_prefix_map = 1;
            repro_cfg.sort_inputs = 1;
            repro_cfg.no_date_macros = 1;
            repro_cfg.strip_metadata = 1;
        }

        rc = now_repro_check(project, cwd, verbose, jobs, &result);
        if (rc == 0)
            printf("reproducible:check — PASS (outputs match)\n");
        else if (rc == 1)
            fprintf(stderr, "reproducible:check — FAIL (outputs differ)\n");
        else
            fprintf(stderr, "error: %s\n", result.message);
        now_repro_free(&repro_cfg);

    } else if (strcmp(phase, "advisory:check") == 0) {
        NowAdvisoryDB adb;
        now_advisory_db_init(&adb);
        int arc = now_advisory_db_load(&adb, &result);
        if (arc != 0) {
            fprintf(stderr, "error: %s\n", result.message);
            now_advisory_db_free(&adb);
            rc = 1;
        } else if (adb.count == 0) {
            printf("No advisory database found. Run 'now advisory:update' first.\n");
        } else {
            /* Get today's date as YYYYMMDD */
            time_t t = time(NULL);
            struct tm *tm = localtime(&t);
            int today = (tm->tm_year + 1900) * 10000 +
                        (tm->tm_mon + 1) * 100 + tm->tm_mday;

            NowAdvisoryReport report2;
            now_advisory_report_init(&report2);
            rc = now_advisory_check_project(&adb, project, today,
                                             &report2, &result);
            char *text = now_advisory_report_format(&report2);
            if (text) { printf("%s", text); free(text); }
            now_advisory_report_free(&report2);
        }
        now_advisory_db_free(&adb);

    } else if (strcmp(phase, "advisory:update") == 0) {
        /* For v1, advisory:update is a placeholder — db must be manually placed */
        printf("advisory:update — not yet implemented (requires HTTP client)\n"
               "Place advisory database at ~/.now/advisories/now-advisory-db.pasta\n");
        rc = 0;

    } else if (strcmp(phase, "verify") == 0) {
        /* Verify archive signature against trust store */
        if (argc < 4) {
            fprintf(stderr, "usage: now verify <archive> <sigfile>\n");
            rc = 1;
        } else {
            const char *archive = argv[2];
            const char *sigfile = argv[3];

            NowTrustPolicy policy = now_trust_policy_from_project(project);
            NowTrustLevel level = now_trust_level(&policy);

            if (level == NOW_TRUST_NONE && verbose)
                fprintf(stderr, "note: trust policy is 'none' — verifying anyway\n");

            /* Look up key from trust store */
            NowTrustStore store;
            now_trust_init(&store);
            now_trust_load(&store, &result);

            const NowTrustKey *tk = NULL;
            if (project->group[0])
                tk = now_trust_find(&store, project->group, project->artifact);

            if (!tk && level == NOW_TRUST_TRUSTED) {
                fprintf(stderr, "error: no trusted key found for %s:%s\n",
                        project->group, project->artifact);
                rc = 1;
            } else if (tk) {
                rc = now_verify_file(archive, sigfile, tk->key, &result);
                if (rc != 0)
                    fprintf(stderr, "error: %s\n", result.message);
                else
                    printf("signature verified\n");
            } else {
                fprintf(stderr, "error: no key available for verification\n");
                rc = 1;
            }

            now_trust_free(&store);
        }

    } else if (strcmp(phase, "-h") == 0 || strcmp(phase, "--help") == 0
               || strcmp(phase, "help") == 0) {
        usage();

    } else {
        fprintf(stderr, "error: unknown phase '%s'\n\n", phase);
        usage();
        rc = 1;
    }

    now_project_free(project);
    return rc;
}
