/*
 * now_plugin.c — Plugin system implementation
 *
 * Handles lifecycle hook dispatch, built-in plugins (now:embed, now:version),
 * and external plugin invocation via stdin/stdout Pasta IPC.
 */
#include "now_plugin.h"
#include "now_fs.h"

#include "pasta.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#ifdef _WIN32
  #include <windows.h>
  #include <direct.h>
  #ifndef strndup
  static char *strndup(const char *s, size_t n) {
      size_t len = strlen(s);
      if (len > n) len = n;
      char *r = (char *)malloc(len + 1);
      if (r) { memcpy(r, s, len); r[len] = '\0'; }
      return r;
  }
  #endif
#else
  #include <unistd.h>
  #include <sys/wait.h>
#endif

/* ---- Result management ---- */

NOW_API void now_plugin_result_init(NowPluginResult *r) {
    memset(r, 0, sizeof(*r));
    r->ok = 1;
    now_strarray_init(&r->sources);
    now_strarray_init(&r->includes);
    now_strarray_init(&r->defines);
    now_strarray_init(&r->messages);
}

NOW_API void now_plugin_result_free(NowPluginResult *r) {
    now_strarray_free(&r->sources);
    now_strarray_free(&r->includes);
    now_strarray_free(&r->defines);
    now_strarray_free(&r->messages);
}

/* ---- Built-in detection ---- */

NOW_API int now_plugin_is_builtin(const char *id) {
    if (!id) return 0;
    return (strncmp(id, "now:", 4) == 0) ? 1 : 0;
}

/* ---- Built-in: now:version ---- */

static int builtin_version(const NowProject *project,
                           const char *basedir,
                           int verbose,
                           NowPluginResult *out,
                           NowResult *result) {
    /* Generate target/generated/_now_version.c */
    char *gen_dir = now_path_join(basedir, "target/generated");
    if (!gen_dir) return -1;
    now_mkdir_p(gen_dir);

    char *out_path = now_path_join(gen_dir, "_now_version.c");
    free(gen_dir);
    if (!out_path) return -1;

    FILE *fp = fopen(out_path, "w");
    if (!fp) {
        if (result) {
            result->code = NOW_ERR_IO;
            snprintf(result->message, sizeof(result->message),
                     "cannot create %s", out_path);
        }
        free(out_path);
        return -1;
    }

    const char *group    = project->group    ? project->group    : "";
    const char *artifact = project->artifact ? project->artifact : "";
    const char *version  = project->version  ? project->version  : "0.0.0";

    /* Parse major.minor.patch */
    int major = 0, minor = 0, patch = 0;
    sscanf(version, "%d.%d.%d", &major, &minor, &patch);

    /* Build timestamp */
    time_t now = time(NULL);
    struct tm *tm = gmtime(&now);
    char ts[32];
    strftime(ts, sizeof(ts), "%Y-%m-%dT%H:%M:%SZ", tm);

    fprintf(fp,
        "/* Auto-generated by now:version — do not edit */\n"
        "const char *NOW_GROUP    = \"%s\";\n"
        "const char *NOW_ARTIFACT = \"%s\";\n"
        "const char *NOW_VERSION  = \"%s\";\n"
        "const int   NOW_VERSION_MAJOR = %d;\n"
        "const int   NOW_VERSION_MINOR = %d;\n"
        "const int   NOW_VERSION_PATCH = %d;\n"
        "const char *NOW_BUILD_TIME = \"%s\";\n",
        group, artifact, version, major, minor, patch, ts);

    fclose(fp);

    if (verbose)
        fprintf(stderr, "  now:version → %s\n", out_path);

    now_strarray_push(&out->sources, out_path);

    /* Add target/generated as include path */
    char *inc = now_path_join(basedir, "target/generated");
    if (inc) {
        now_strarray_push(&out->includes, inc);
        free(inc);
    }

    free(out_path);
    return 0;
}

/* ---- Built-in: now:embed ---- */

static int builtin_embed(const NowPlugin *plugin,
                         const NowProject *project,
                         const char *basedir,
                         int verbose,
                         NowPluginResult *out,
                         NowResult *result) {
    /* Config: { src: "assets/", prefix: "asset_" } */
    const char *src_dir = "assets";
    const char *prefix = "embed_";

    if (plugin->config) {
        const PastaValue *cfg = (const PastaValue *)plugin->config;
        if (pasta_type(cfg) == PASTA_MAP) {
            const PastaValue *v;
            v = pasta_map_get(cfg, "src");
            if (v && pasta_type(v) == PASTA_STRING)
                src_dir = pasta_get_string(v);
            v = pasta_map_get(cfg, "prefix");
            if (v && pasta_type(v) == PASTA_STRING)
                prefix = pasta_get_string(v);
        }
    }

    /* Find files in src_dir */
    char *abs_src = now_path_join(basedir, src_dir);
    if (!abs_src || !now_path_exists(abs_src)) {
        free(abs_src);
        /* No assets dir — not an error, just skip */
        if (verbose)
            fprintf(stderr, "  now:embed: no directory '%s', skipping\n", src_dir);
        return 0;
    }

    NowFileList files;
    now_filelist_init(&files);
    now_discover_sources(basedir, src_dir, NULL, &files);

    if (files.count == 0) {
        now_filelist_free(&files);
        free(abs_src);
        return 0;
    }

    /* Generate target/generated/_now_embed.c */
    char *gen_dir = now_path_join(basedir, "target/generated");
    if (!gen_dir) { now_filelist_free(&files); free(abs_src); return -1; }
    now_mkdir_p(gen_dir);

    char *out_path = now_path_join(gen_dir, "_now_embed.c");
    free(gen_dir);
    if (!out_path) { now_filelist_free(&files); free(abs_src); return -1; }

    FILE *fp = fopen(out_path, "w");
    if (!fp) {
        if (result) {
            result->code = NOW_ERR_IO;
            snprintf(result->message, sizeof(result->message),
                     "cannot create %s", out_path);
        }
        now_filelist_free(&files);
        free(abs_src);
        free(out_path);
        return -1;
    }

    fprintf(fp, "/* Auto-generated by now:embed — do not edit */\n"
                "#include <stddef.h>\n\n");

    for (size_t i = 0; i < files.count; i++) {
        const char *fpath = files.paths[i];

        /* Read file */
        FILE *in = fopen(fpath, "rb");
        if (!in) continue;

        fseek(in, 0, SEEK_END);
        long flen = ftell(in);
        fseek(in, 0, SEEK_SET);

        unsigned char *data = (unsigned char *)malloc((size_t)flen);
        if (!data) { fclose(in); continue; }
        size_t nread = fread(data, 1, (size_t)flen, in);
        fclose(in);

        /* Build variable name from filename: sanitize to C identifier */
        const char *fname = fpath;
        /* Strip abs_src prefix */
        if (strncmp(fpath, abs_src, strlen(abs_src)) == 0) {
            fname = fpath + strlen(abs_src);
            while (*fname == '/' || *fname == '\\') fname++;
        }

        char varname[256];
        snprintf(varname, sizeof(varname), "%s", prefix);
        size_t vlen = strlen(varname);
        for (const char *c = fname; *c && vlen < sizeof(varname) - 1; c++) {
            if ((*c >= 'a' && *c <= 'z') || (*c >= 'A' && *c <= 'Z') ||
                (*c >= '0' && *c <= '9'))
                varname[vlen++] = *c;
            else
                varname[vlen++] = '_';
        }
        varname[vlen] = '\0';

        fprintf(fp, "const unsigned char %s[] = {\n    ", varname);
        for (size_t b = 0; b < nread; b++) {
            fprintf(fp, "0x%02x", data[b]);
            if (b + 1 < nread) {
                fprintf(fp, ",");
                if ((b + 1) % 12 == 0) fprintf(fp, "\n    ");
            }
        }
        fprintf(fp, "\n};\n");
        fprintf(fp, "const size_t %s_len = %zu;\n\n", varname, nread);

        free(data);

        if (verbose)
            fprintf(stderr, "  now:embed: %s → %s (%zu bytes)\n",
                    fname, varname, nread);
    }

    fclose(fp);
    now_strarray_push(&out->sources, out_path);

    char *inc = now_path_join(basedir, "target/generated");
    if (inc) {
        now_strarray_push(&out->includes, inc);
        free(inc);
    }

    now_filelist_free(&files);
    free(abs_src);
    free(out_path);
    return 0;
}

/* ---- External plugin invocation ---- */

/* Parse plugin response Pasta from stdout */
static int parse_plugin_response(const char *output, size_t len,
                                  NowPluginResult *out,
                                  NowResult *result) {
    PastaResult pr;
    PastaValue *root = pasta_parse(output, len, &pr);
    if (!root || pr.code != PASTA_OK) {
        if (result) {
            result->code = NOW_ERR_SYNTAX;
            snprintf(result->message, sizeof(result->message),
                     "plugin output: %s", pr.message);
        }
        return -1;
    }

    if (pasta_type(root) != PASTA_MAP) {
        pasta_free(root);
        if (result) {
            result->code = NOW_ERR_SCHEMA;
            snprintf(result->message, sizeof(result->message),
                     "plugin output must be a map");
        }
        return -1;
    }

    /* status: ok | warn | error */
    const PastaValue *status_val = pasta_map_get(root, "status");
    if (status_val && pasta_type(status_val) == PASTA_STRING) {
        const char *s = pasta_get_string(status_val);
        if (strcmp(s, "error") == 0)
            out->ok = 0;
    }

    /* sources: [...] */
    const PastaValue *sources = pasta_map_get(root, "sources");
    if (sources && pasta_type(sources) == PASTA_ARRAY) {
        size_t n = pasta_count(sources);
        for (size_t i = 0; i < n; i++) {
            const PastaValue *v = pasta_array_get(sources, i);
            if (v && pasta_type(v) == PASTA_STRING)
                now_strarray_push(&out->sources, pasta_get_string(v));
        }
    }

    /* includes: [...] */
    const PastaValue *includes = pasta_map_get(root, "includes");
    if (includes && pasta_type(includes) == PASTA_ARRAY) {
        size_t n = pasta_count(includes);
        for (size_t i = 0; i < n; i++) {
            const PastaValue *v = pasta_array_get(includes, i);
            if (v && pasta_type(v) == PASTA_STRING)
                now_strarray_push(&out->includes, pasta_get_string(v));
        }
    }

    /* defines: [...] */
    const PastaValue *defines = pasta_map_get(root, "defines");
    if (defines && pasta_type(defines) == PASTA_ARRAY) {
        size_t n = pasta_count(defines);
        for (size_t i = 0; i < n; i++) {
            const PastaValue *v = pasta_array_get(defines, i);
            if (v && pasta_type(v) == PASTA_STRING)
                now_strarray_push(&out->defines, pasta_get_string(v));
        }
    }

    /* messages: [{level, text}...] */
    const PastaValue *msgs = pasta_map_get(root, "messages");
    if (msgs && pasta_type(msgs) == PASTA_ARRAY) {
        size_t n = pasta_count(msgs);
        for (size_t i = 0; i < n; i++) {
            const PastaValue *m = pasta_array_get(msgs, i);
            if (!m || pasta_type(m) != PASTA_MAP) continue;
            const PastaValue *text = pasta_map_get(m, "text");
            const PastaValue *level = pasta_map_get(m, "level");
            if (text && pasta_type(text) == PASTA_STRING) {
                char msg[512];
                const char *lv = (level && pasta_type(level) == PASTA_STRING)
                                 ? pasta_get_string(level) : "info";
                snprintf(msg, sizeof(msg), "[%s] %s", lv, pasta_get_string(text));
                now_strarray_push(&out->messages, msg);
            }
        }
    }

    pasta_free(root);
    return out->ok ? 0 : -1;
}

/* Build the Pasta input payload for a plugin */
static char *build_plugin_input(const NowPlugin *plugin,
                                 const NowProject *project,
                                 const char *basedir,
                                 const char *hook) {
    /* Build input as Pasta text */
    char *target = now_path_join(basedir, "target");

    /* We use a simple string builder approach */
    char buf[4096];
    int n = snprintf(buf, sizeof(buf),
        "{\n"
        "  hook: \"%s\",\n"
        "  project: \"%s\",\n"
        "  basedir: \"%s\",\n"
        "  target: \"%s\"",
        hook, basedir, basedir, target ? target : "");

    free(target);

    /* Add config if present */
    if (plugin->config) {
        const PastaValue *cfg = (const PastaValue *)plugin->config;
        char *cfg_str = pasta_write(cfg, 0);
        if (cfg_str) {
            n += snprintf(buf + n, sizeof(buf) - (size_t)n,
                         ",\n  config: %s", cfg_str);
            free(cfg_str);
        }
    }

    n += snprintf(buf + n, sizeof(buf) - (size_t)n, "\n}\n");
    return strdup(buf);
}

/* Invoke an external plugin as a child process with stdin/stdout IPC */
static int invoke_external(const NowPlugin *plugin,
                           const NowProject *project,
                           const char *basedir,
                           const char *hook,
                           int verbose,
                           NowPluginResult *out,
                           NowResult *result) {
    /* Build the plugin executable path */
    const char *home = NULL;
#ifdef _WIN32
    home = getenv("USERPROFILE");
    if (!home) home = getenv("HOME");
#else
    home = getenv("HOME");
#endif
    if (!home) {
        if (result) {
            result->code = NOW_ERR_NOT_FOUND;
            snprintf(result->message, sizeof(result->message),
                     "cannot determine home directory");
        }
        return -1;
    }

    /* Parse plugin ID to find executable */
    /* For now, assume plugin binary is at ~/.now/repo/{group}/{artifact}/{version}/bin/{artifact} */
    char *input = build_plugin_input(plugin, project, basedir, hook);
    if (!input) return -1;

    if (verbose)
        fprintf(stderr, "  plugin %s: invoking for hook '%s'\n", plugin->id, hook);

    /* TODO: full external process invocation with pipes
     * For now, this is a placeholder that returns an error */
    free(input);
    if (result) {
        result->code = NOW_ERR_NOT_FOUND;
        snprintf(result->message, sizeof(result->message),
                 "external plugin '%s' invocation not yet implemented", plugin->id);
    }
    return -1;
}

/* ---- Single plugin invocation ---- */

NOW_API int now_plugin_invoke(const NowPlugin *plugin,
                               const NowProject *project,
                               const char *basedir,
                               const char *hook,
                               int verbose,
                               NowPluginResult *out,
                               NowResult *result) {
    if (!plugin || !plugin->id) return -1;

    if (now_plugin_is_builtin(plugin->id)) {
        /* Dispatch built-in plugins */
        if (strcmp(plugin->id, "now:version") == 0)
            return builtin_version(project, basedir, verbose, out, result);
        if (strcmp(plugin->id, "now:embed") == 0)
            return builtin_embed(plugin, project, basedir, verbose, out, result);

        /* Unknown built-in */
        if (result) {
            result->code = NOW_ERR_NOT_FOUND;
            snprintf(result->message, sizeof(result->message),
                     "unknown built-in plugin '%s'", plugin->id);
        }
        return -1;
    }

    /* External plugin */
    return invoke_external(plugin, project, basedir, hook, verbose, out, result);
}

/* ---- Hook dispatch ---- */

NOW_API int now_plugin_run_hook(const NowProject *project,
                                 const char *basedir,
                                 const char *hook,
                                 int verbose,
                                 NowPluginResult *out,
                                 NowResult *result) {
    if (!project || !hook) return 0;
    if (project->plugins.count == 0) return 0;

    now_plugin_result_init(out);

    for (size_t i = 0; i < project->plugins.count; i++) {
        const NowPlugin *pl = &project->plugins.items[i];

        /* Skip plugins not registered for this hook */
        if (!pl->phase || strcmp(pl->phase, hook) != 0)
            continue;

        if (verbose)
            fprintf(stderr, "  hook '%s': running plugin '%s'\n", hook, pl->id);

        NowPluginResult single;
        now_plugin_result_init(&single);

        int rc = now_plugin_invoke(pl, project, basedir, hook, verbose,
                                    &single, result);

        /* Merge single result into aggregate */
        for (size_t s = 0; s < single.sources.count; s++)
            now_strarray_push(&out->sources, single.sources.items[s]);
        for (size_t s = 0; s < single.includes.count; s++)
            now_strarray_push(&out->includes, single.includes.items[s]);
        for (size_t s = 0; s < single.defines.count; s++)
            now_strarray_push(&out->defines, single.defines.items[s]);
        for (size_t s = 0; s < single.messages.count; s++) {
            fprintf(stderr, "  %s: %s\n", pl->id, single.messages.items[s]);
            now_strarray_push(&out->messages, single.messages.items[s]);
        }

        now_plugin_result_free(&single);

        if (rc != 0) {
            out->ok = 0;
            return -1;  /* Stop chain on error */
        }
    }

    return 0;
}
