/*
 * now_export.c — Export now.pasta as CMakeLists.txt
 *
 * Generates a working CMakeLists.txt from a NowProject descriptor.
 * The generated file is standalone — no dependency on now at build time.
 */
#include "now_export.h"
#include "now_pom.h"
#include "now_fs.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Map now optimization levels to CMake equivalents */
static const char *cmake_opt_flags(const char *opt) {
    if (!opt) return NULL;
    if (strcmp(opt, "none") == 0)  return "-O0";
    if (strcmp(opt, "debug") == 0) return "-Og";
    if (strcmp(opt, "size") == 0)  return "-Os";
    if (strcmp(opt, "speed") == 0) return "-O2";
    if (strcmp(opt, "lto") == 0)   return "-O2 -flto";
    return NULL;
}

/* Map now C/C++ std to CMake standard number */
static int cmake_c_std(const char *std_str) {
    if (!std_str) return 11;
    if (strcmp(std_str, "c89") == 0 || strcmp(std_str, "c90") == 0) return 90;
    if (strcmp(std_str, "c99") == 0) return 99;
    if (strcmp(std_str, "c11") == 0) return 11;
    if (strcmp(std_str, "c17") == 0 || strcmp(std_str, "c18") == 0) return 17;
    if (strcmp(std_str, "c23") == 0) return 23;
    return 11;
}

static int cmake_cxx_std(const char *std_str) {
    if (!std_str) return 17;
    if (strcmp(std_str, "c++11") == 0) return 11;
    if (strcmp(std_str, "c++14") == 0) return 14;
    if (strcmp(std_str, "c++17") == 0) return 17;
    if (strcmp(std_str, "c++20") == 0) return 20;
    if (strcmp(std_str, "c++23") == 0) return 23;
    return 17;
}

/* Check if the project uses C++ */
static int has_cxx(const NowProject *p) {
    for (size_t i = 0; i < p->langs.count; i++) {
        if (strcmp(p->langs.items[i], "c++") == 0 ||
            strcmp(p->langs.items[i], "cxx") == 0 ||
            strcmp(p->langs.items[i], "cpp") == 0)
            return 1;
    }
    return 0;
}

/* Source glob patterns for CMake file(GLOB_RECURSE ...) */
static const char *c_glob_patterns =
    "\"${CMAKE_SOURCE_DIR}/%s/*.c\"\n"
    "    \"${CMAKE_SOURCE_DIR}/%s/*.i\"";

static const char *cxx_glob_patterns =
    "\"${CMAKE_SOURCE_DIR}/%s/*.cpp\"\n"
    "    \"${CMAKE_SOURCE_DIR}/%s/*.cxx\"\n"
    "    \"${CMAKE_SOURCE_DIR}/%s/*.cc\"";

NOW_API int now_export_cmake(const NowProject *project, const char *basedir,
                              const char *outpath, NowResult *result) {
    if (!project || !outpath) {
        if (result) {
            result->code = NOW_ERR_SCHEMA;
            snprintf(result->message, sizeof(result->message),
                     "export:cmake: project and outpath required");
        }
        return -1;
    }

    FILE *fp = fopen(outpath, "w");
    if (!fp) {
        if (result) {
            result->code = NOW_ERR_IO;
            snprintf(result->message, sizeof(result->message),
                     "export:cmake: cannot write %s", outpath);
        }
        return -1;
    }

    const char *artifact = project->artifact ? project->artifact : "project";
    const char *version  = project->version  ? project->version  : "0.1.0";
    const char *out_type = project->output.type ? project->output.type : "executable";
    const char *out_name = project->output.name ? project->output.name : artifact;
    int use_cxx = has_cxx(project);

    /* Source directory (default: src/main/c or src/main/cpp) */
    const char *src_dir = project->sources.dir;
    if (!src_dir) src_dir = use_cxx ? "src/main/cpp" : "src/main/c";

    /* Header directory */
    const char *hdr_dir = project->sources.headers;
    if (!hdr_dir) hdr_dir = use_cxx ? "src/main/hpp" : "src/main/h";

    /* Test directory */
    const char *test_dir = project->tests.dir;
    if (!test_dir) test_dir = use_cxx ? "src/test/cpp" : "src/test/c";

    /* ---- Header ---- */
    fprintf(fp, "# Generated by now %s — do not edit.\n", now_version());
    fprintf(fp, "# Regenerate with: now export:cmake\n");
    fprintf(fp, "# Source: now.pasta\n");
    fprintf(fp, "#\n");
    if (project->name)
        fprintf(fp, "# %s", project->name);
    if (project->description)
        fprintf(fp, " — %s", project->description);
    if (project->name || project->description)
        fprintf(fp, "\n");
    fprintf(fp, "\n");

    /* ---- CMake preamble ---- */
    fprintf(fp, "cmake_minimum_required(VERSION 3.20)\n");

    /* Languages */
    fprintf(fp, "project(%s VERSION %s LANGUAGES", artifact, version);
    if (use_cxx) fprintf(fp, " CXX");
    fprintf(fp, " C)\n\n");

    /* Standards */
    if (use_cxx) {
        int cxx_ver = cmake_cxx_std(project->std);
        fprintf(fp, "set(CMAKE_CXX_STANDARD %d)\n", cxx_ver);
        fprintf(fp, "set(CMAKE_CXX_STANDARD_REQUIRED ON)\n");
    }
    int c_ver = cmake_c_std(project->std);
    fprintf(fp, "set(CMAKE_C_STANDARD %d)\n", c_ver);
    fprintf(fp, "set(CMAKE_C_STANDARD_REQUIRED ON)\n");
    fprintf(fp, "\n");

    /* ---- Source discovery ---- */
    fprintf(fp, "# Source files\n");
    fprintf(fp, "file(GLOB_RECURSE SOURCES\n");
    fprintf(fp, "    ");
    fprintf(fp, c_glob_patterns, src_dir, src_dir);
    fprintf(fp, "\n");
    if (use_cxx) {
        fprintf(fp, "    ");
        fprintf(fp, cxx_glob_patterns, src_dir, src_dir, src_dir);
        fprintf(fp, "\n");
    }
    fprintf(fp, ")\n\n");

    /* ---- Target definition ---- */
    if (strcmp(out_type, "executable") == 0) {
        fprintf(fp, "add_executable(%s ${SOURCES})\n", out_name);
    } else if (strcmp(out_type, "static") == 0) {
        fprintf(fp, "add_library(%s STATIC ${SOURCES})\n", out_name);
    } else if (strcmp(out_type, "shared") == 0) {
        fprintf(fp, "add_library(%s SHARED ${SOURCES})\n", out_name);
    } else if (strcmp(out_type, "header-only") == 0) {
        fprintf(fp, "add_library(%s INTERFACE)\n", out_name);
    } else {
        fprintf(fp, "add_executable(%s ${SOURCES})\n", out_name);
    }
    fprintf(fp, "\n");

    /* ---- Include directories ---- */
    if (strcmp(out_type, "header-only") == 0) {
        fprintf(fp, "target_include_directories(%s INTERFACE\n", out_name);
        fprintf(fp, "    $<BUILD_INTERFACE:${CMAKE_SOURCE_DIR}/%s>\n", hdr_dir);
        fprintf(fp, "    $<INSTALL_INTERFACE:include>\n");
        fprintf(fp, ")\n\n");
    } else {
        fprintf(fp, "target_include_directories(%s\n", out_name);
        fprintf(fp, "    PUBLIC  $<BUILD_INTERFACE:${CMAKE_SOURCE_DIR}/%s>\n", hdr_dir);
        fprintf(fp, "            $<INSTALL_INTERFACE:include>\n");
        fprintf(fp, "    PRIVATE ${CMAKE_SOURCE_DIR}/%s\n", src_dir);
        fprintf(fp, ")\n\n");

        /* Extra include paths from compile.includes */
        if (project->compile.includes.count > 0) {
            fprintf(fp, "target_include_directories(%s PRIVATE\n", out_name);
            for (size_t i = 0; i < project->compile.includes.count; i++)
                fprintf(fp, "    ${CMAKE_SOURCE_DIR}/%s\n",
                        project->compile.includes.items[i]);
            fprintf(fp, ")\n\n");
        }
    }

    /* ---- Compile options ---- */
    if (project->compile.warnings.count > 0 ||
        project->compile.flags.count > 0 ||
        project->compile.opt) {
        fprintf(fp, "target_compile_options(%s PRIVATE\n", out_name);

        /* Warnings */
        for (size_t i = 0; i < project->compile.warnings.count; i++)
            fprintf(fp, "    -%s\n", project->compile.warnings.items[i]);

        /* Optimization */
        const char *opt = cmake_opt_flags(project->compile.opt);
        if (opt) fprintf(fp, "    %s\n", opt);

        /* Raw flags */
        for (size_t i = 0; i < project->compile.flags.count; i++)
            fprintf(fp, "    %s\n", project->compile.flags.items[i]);

        fprintf(fp, ")\n\n");
    }

    /* ---- Compile definitions ---- */
    if (project->compile.defines.count > 0) {
        fprintf(fp, "target_compile_definitions(%s PRIVATE\n", out_name);
        for (size_t i = 0; i < project->compile.defines.count; i++)
            fprintf(fp, "    %s\n", project->compile.defines.items[i]);
        fprintf(fp, ")\n\n");
    }

    /* ---- Link options ---- */
    if (project->link.flags.count > 0) {
        fprintf(fp, "target_link_options(%s PRIVATE\n", out_name);
        for (size_t i = 0; i < project->link.flags.count; i++)
            fprintf(fp, "    %s\n", project->link.flags.items[i]);
        fprintf(fp, ")\n\n");
    }

    /* ---- Link libraries ---- */
    if (project->link.libs.count > 0 || project->link.libdirs.count > 0) {
        if (project->link.libdirs.count > 0) {
            fprintf(fp, "target_link_directories(%s PRIVATE\n", out_name);
            for (size_t i = 0; i < project->link.libdirs.count; i++)
                fprintf(fp, "    %s\n", project->link.libdirs.items[i]);
            fprintf(fp, ")\n\n");
        }
        if (project->link.libs.count > 0) {
            fprintf(fp, "target_link_libraries(%s PRIVATE\n", out_name);
            for (size_t i = 0; i < project->link.libs.count; i++)
                fprintf(fp, "    %s\n", project->link.libs.items[i]);
            fprintf(fp, ")\n\n");
        }
    }

    /* ---- Dependencies (as comments — cannot auto-resolve) ---- */
    if (project->deps.count > 0) {
        fprintf(fp, "# Dependencies from now.pasta (resolve manually or use FetchContent):\n");
        for (size_t i = 0; i < project->deps.count; i++) {
            const NowDep *d = &project->deps.items[i];
            fprintf(fp, "#   %s", d->id);
            if (d->scope && strcmp(d->scope, "compile") != 0)
                fprintf(fp, "  (scope: %s)", d->scope);
            if (d->optional)
                fprintf(fp, "  (optional)");
            fprintf(fp, "\n");
        }
        fprintf(fp, "#\n");
        fprintf(fp, "# Example using FetchContent:\n");
        fprintf(fp, "# include(FetchContent)\n");
        fprintf(fp, "# FetchContent_Declare(dep_name URL <url>)\n");
        fprintf(fp, "# FetchContent_MakeAvailable(dep_name)\n");
        fprintf(fp, "# target_link_libraries(%s PRIVATE dep_name)\n", out_name);
        fprintf(fp, "\n");
    }

    /* ---- Test target ---- */
    fprintf(fp, "# Test target\n");
    fprintf(fp, "option(%s_BUILD_TESTS \"Build test executable\" ON)\n", artifact);
    fprintf(fp, "if(%s_BUILD_TESTS)\n", artifact);
    fprintf(fp, "    file(GLOB_RECURSE TEST_SOURCES\n");
    fprintf(fp, "        ");
    fprintf(fp, c_glob_patterns, test_dir, test_dir);
    fprintf(fp, "\n");
    if (use_cxx) {
        fprintf(fp, "        ");
        fprintf(fp, cxx_glob_patterns, test_dir, test_dir, test_dir);
        fprintf(fp, "\n");
    }
    fprintf(fp, "    )\n");
    fprintf(fp, "    if(TEST_SOURCES)\n");
    if (strcmp(out_type, "executable") == 0) {
        /* For executables, test links against sources directly (minus main) */
        fprintf(fp, "        add_executable(%s_test ${TEST_SOURCES} ${SOURCES})\n",
                artifact);
    } else {
        /* For libraries, test links against the library */
        fprintf(fp, "        add_executable(%s_test ${TEST_SOURCES})\n", artifact);
        fprintf(fp, "        target_link_libraries(%s_test PRIVATE %s)\n",
                artifact, out_name);
    }
    fprintf(fp, "        target_include_directories(%s_test PRIVATE\n", artifact);
    fprintf(fp, "            ${CMAKE_SOURCE_DIR}/%s\n", hdr_dir);
    fprintf(fp, "            ${CMAKE_SOURCE_DIR}/%s\n", src_dir);
    fprintf(fp, "        )\n");
    fprintf(fp, "    endif()\n");
    fprintf(fp, "endif()\n\n");

    /* ---- Install rules ---- */
    fprintf(fp, "# Install rules\n");
    fprintf(fp, "include(GNUInstallDirs)\n");
    if (strcmp(out_type, "header-only") == 0) {
        fprintf(fp, "install(DIRECTORY %s/ DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})\n",
                hdr_dir);
    } else {
        fprintf(fp, "install(TARGETS %s\n", out_name);
        fprintf(fp, "    RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}\n");
        fprintf(fp, "    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}\n");
        fprintf(fp, "    ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}\n");
        fprintf(fp, ")\n");
        fprintf(fp, "install(DIRECTORY %s/ DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})\n",
                hdr_dir);
    }
    fprintf(fp, "\n");

    fclose(fp);

    if (result) {
        result->code = NOW_OK;
        snprintf(result->message, sizeof(result->message),
                 "wrote %s", outpath);
    }
    return 0;
}

/* ---- export:make ---- */

/* Map now optimization level to GCC/Clang -O flag */
static const char *make_opt_flag(const char *opt) {
    if (!opt) return "-O0";
    if (strcmp(opt, "none") == 0)  return "-O0";
    if (strcmp(opt, "debug") == 0) return "-Og";
    if (strcmp(opt, "size") == 0)  return "-Os";
    if (strcmp(opt, "speed") == 0) return "-O2";
    if (strcmp(opt, "lto") == 0)   return "-O2 -flto";
    return "-O0";
}

NOW_API int now_export_make(const NowProject *project, const char *basedir,
                              const char *outpath, NowResult *result) {
    if (!project || !outpath) {
        if (result) {
            result->code = NOW_ERR_SCHEMA;
            snprintf(result->message, sizeof(result->message),
                     "export:make: project and outpath required");
        }
        return -1;
    }

    FILE *fp = fopen(outpath, "w");
    if (!fp) {
        if (result) {
            result->code = NOW_ERR_IO;
            snprintf(result->message, sizeof(result->message),
                     "export:make: cannot write %s", outpath);
        }
        return -1;
    }

    const char *artifact = project->artifact ? project->artifact : "project";
    const char *version  = project->version  ? project->version  : "0.1.0";
    const char *out_type = project->output.type ? project->output.type : "executable";
    const char *out_name = project->output.name ? project->output.name : artifact;
    int use_cxx = has_cxx(project);

    /* Source directory */
    const char *src_dir = project->sources.dir;
    if (!src_dir) src_dir = use_cxx ? "src/main/cpp" : "src/main/c";

    /* Header directory */
    const char *hdr_dir = project->sources.headers;
    if (!hdr_dir) hdr_dir = use_cxx ? "src/main/hpp" : "src/main/h";

    /* Test directory */
    const char *test_dir = project->tests.dir;
    if (!test_dir) test_dir = use_cxx ? "src/test/cpp" : "src/test/c";

    /* Compiler */
    const char *cc = use_cxx ? "CXX" : "CC";
    const char *cc_default = use_cxx ? "g++" : "gcc";

    /* ---- Header ---- */
    fprintf(fp, "# Generated by now %s — do not edit.\n", now_version());
    fprintf(fp, "# Regenerate with: now export:make\n");
    fprintf(fp, "# Source: now.pasta\n");
    fprintf(fp, "#\n");
    if (project->name)
        fprintf(fp, "# %s", project->name);
    if (project->description)
        fprintf(fp, " — %s", project->description);
    if (project->name || project->description)
        fprintf(fp, "\n");
    fprintf(fp, "\n");

    /* ---- Variables ---- */
    fprintf(fp, "# Project\n");
    fprintf(fp, "PROJECT  := %s\n", artifact);
    fprintf(fp, "VERSION  := %s\n", version);
    fprintf(fp, "TARGET   := %s\n", out_name);
    fprintf(fp, "\n");

    fprintf(fp, "# Toolchain\n");
    fprintf(fp, "%s       ?= %s\n", cc, cc_default);
    fprintf(fp, "AR       ?= ar\n");
    fprintf(fp, "\n");

    /* Directories */
    fprintf(fp, "# Directories\n");
    fprintf(fp, "SRC_DIR  := %s\n", src_dir);
    fprintf(fp, "HDR_DIR  := %s\n", hdr_dir);
    fprintf(fp, "TEST_DIR := %s\n", test_dir);
    fprintf(fp, "BUILD_DIR := target\n");
    fprintf(fp, "OBJ_DIR  := $(BUILD_DIR)/obj\n");
    fprintf(fp, "\n");

    /* Source discovery */
    fprintf(fp, "# Sources\n");
    if (use_cxx) {
        fprintf(fp, "SOURCES  := $(wildcard $(SRC_DIR)/*.c) "
                    "$(wildcard $(SRC_DIR)/*.cpp) "
                    "$(wildcard $(SRC_DIR)/*.cxx) "
                    "$(wildcard $(SRC_DIR)/*.cc)\n");
    } else {
        fprintf(fp, "SOURCES  := $(wildcard $(SRC_DIR)/*.c)\n");
    }
    fprintf(fp, "OBJECTS  := $(patsubst $(SRC_DIR)/%%, $(OBJ_DIR)/%%.o, "
                "$(SOURCES))\n");
    fprintf(fp, "\n");

    /* Test sources */
    fprintf(fp, "# Test sources\n");
    if (use_cxx) {
        fprintf(fp, "TEST_SOURCES := $(wildcard $(TEST_DIR)/*.c) "
                    "$(wildcard $(TEST_DIR)/*.cpp) "
                    "$(wildcard $(TEST_DIR)/*.cxx) "
                    "$(wildcard $(TEST_DIR)/*.cc)\n");
    } else {
        fprintf(fp, "TEST_SOURCES := $(wildcard $(TEST_DIR)/*.c)\n");
    }
    fprintf(fp, "TEST_OBJECTS := $(patsubst $(TEST_DIR)/%%, "
                "$(OBJ_DIR)/test_%%.o, $(TEST_SOURCES))\n");
    fprintf(fp, "\n");

    /* Flags */
    fprintf(fp, "# Flags\n");

    /* Standard */
    if (project->std) {
        fprintf(fp, "CFLAGS   += -std=%s\n", project->std);
    } else {
        fprintf(fp, "CFLAGS   += %s\n",
                use_cxx ? "-std=c++17" : "-std=c11");
    }

    /* Include paths */
    fprintf(fp, "CFLAGS   += -I$(HDR_DIR) -I$(SRC_DIR)\n");
    for (size_t i = 0; i < project->compile.includes.count; i++)
        fprintf(fp, "CFLAGS   += -I%s\n", project->compile.includes.items[i]);

    /* Warnings */
    for (size_t i = 0; i < project->compile.warnings.count; i++)
        fprintf(fp, "CFLAGS   += -%s\n", project->compile.warnings.items[i]);

    /* Optimization */
    fprintf(fp, "CFLAGS   += %s\n", make_opt_flag(project->compile.opt));

    /* Defines */
    for (size_t i = 0; i < project->compile.defines.count; i++)
        fprintf(fp, "CFLAGS   += -D%s\n", project->compile.defines.items[i]);

    /* Raw compile flags */
    for (size_t i = 0; i < project->compile.flags.count; i++)
        fprintf(fp, "CFLAGS   += %s\n", project->compile.flags.items[i]);

    fprintf(fp, "\n");

    /* Linker flags */
    fprintf(fp, "LDFLAGS  :=\n");
    for (size_t i = 0; i < project->link.libdirs.count; i++)
        fprintf(fp, "LDFLAGS  += -L%s\n", project->link.libdirs.items[i]);
    for (size_t i = 0; i < project->link.flags.count; i++)
        fprintf(fp, "LDFLAGS  += %s\n", project->link.flags.items[i]);

    fprintf(fp, "LDLIBS   :=\n");
    for (size_t i = 0; i < project->link.libs.count; i++)
        fprintf(fp, "LDLIBS   += -l%s\n", project->link.libs.items[i]);
    fprintf(fp, "\n");

    /* Output-type-specific settings */
    if (strcmp(out_type, "shared") == 0) {
        fprintf(fp, "# Shared library\n");
        fprintf(fp, "CFLAGS   += -fPIC\n");
        fprintf(fp, "OUTPUT   := $(BUILD_DIR)/lib$(TARGET).so\n");
    } else if (strcmp(out_type, "static") == 0) {
        fprintf(fp, "# Static library\n");
        fprintf(fp, "OUTPUT   := $(BUILD_DIR)/lib$(TARGET).a\n");
    } else {
        fprintf(fp, "# Executable\n");
        fprintf(fp, "OUTPUT   := $(BUILD_DIR)/$(TARGET)\n");
    }
    fprintf(fp, "\n");

    /* Dependencies (as comments) */
    if (project->deps.count > 0) {
        fprintf(fp, "# Dependencies from now.pasta (resolve manually):\n");
        for (size_t i = 0; i < project->deps.count; i++) {
            const NowDep *d = &project->deps.items[i];
            fprintf(fp, "#   %s", d->id);
            if (d->scope && strcmp(d->scope, "compile") != 0)
                fprintf(fp, "  (scope: %s)", d->scope);
            if (d->optional)
                fprintf(fp, "  (optional)");
            fprintf(fp, "\n");
        }
        fprintf(fp, "\n");
    }

    /* ---- Phony targets ---- */
    fprintf(fp, "# ---- Targets ----\n\n");
    fprintf(fp, ".PHONY: all clean test install\n\n");
    fprintf(fp, "all: $(OUTPUT)\n\n");

    /* ---- Build rules ---- */
    if (strcmp(out_type, "shared") == 0) {
        fprintf(fp, "$(OUTPUT): $(OBJECTS)\n");
        fprintf(fp, "\t@mkdir -p $(dir $@)\n");
        fprintf(fp, "\t$(%s) -shared -o $@ $^ $(LDFLAGS) $(LDLIBS)\n\n", cc);
    } else if (strcmp(out_type, "static") == 0) {
        fprintf(fp, "$(OUTPUT): $(OBJECTS)\n");
        fprintf(fp, "\t@mkdir -p $(dir $@)\n");
        fprintf(fp, "\t$(AR) rcs $@ $^\n\n");
    } else {
        fprintf(fp, "$(OUTPUT): $(OBJECTS)\n");
        fprintf(fp, "\t@mkdir -p $(dir $@)\n");
        fprintf(fp, "\t$(%s) -o $@ $^ $(LDFLAGS) $(LDLIBS)\n\n", cc);
    }

    /* Object compilation rule */
    fprintf(fp, "$(OBJ_DIR)/%%.c.o: $(SRC_DIR)/%%.c\n");
    fprintf(fp, "\t@mkdir -p $(dir $@)\n");
    fprintf(fp, "\t$(%s) $(CFLAGS) -c -o $@ $<\n\n", cc);

    if (use_cxx) {
        fprintf(fp, "$(OBJ_DIR)/%%.cpp.o: $(SRC_DIR)/%%.cpp\n");
        fprintf(fp, "\t@mkdir -p $(dir $@)\n");
        fprintf(fp, "\t$(%s) $(CFLAGS) -c -o $@ $<\n\n", cc);

        fprintf(fp, "$(OBJ_DIR)/%%.cxx.o: $(SRC_DIR)/%%.cxx\n");
        fprintf(fp, "\t@mkdir -p $(dir $@)\n");
        fprintf(fp, "\t$(%s) $(CFLAGS) -c -o $@ $<\n\n", cc);

        fprintf(fp, "$(OBJ_DIR)/%%.cc.o: $(SRC_DIR)/%%.cc\n");
        fprintf(fp, "\t@mkdir -p $(dir $@)\n");
        fprintf(fp, "\t$(%s) $(CFLAGS) -c -o $@ $<\n\n", cc);
    }

    /* ---- Test target ---- */
    fprintf(fp, "# Test\n");
    fprintf(fp, "$(OBJ_DIR)/test_%%.c.o: $(TEST_DIR)/%%.c\n");
    fprintf(fp, "\t@mkdir -p $(dir $@)\n");
    fprintf(fp, "\t$(%s) $(CFLAGS) -c -o $@ $<\n\n", cc);

    if (use_cxx) {
        fprintf(fp, "$(OBJ_DIR)/test_%%.cpp.o: $(TEST_DIR)/%%.cpp\n");
        fprintf(fp, "\t@mkdir -p $(dir $@)\n");
        fprintf(fp, "\t$(%s) $(CFLAGS) -c -o $@ $<\n\n", cc);
    }

    if (strcmp(out_type, "executable") == 0) {
        /* For executables, link test with all source objects (caller excludes main) */
        fprintf(fp, "test: $(TEST_OBJECTS) $(OBJECTS)\n");
        fprintf(fp, "\t@mkdir -p $(BUILD_DIR)\n");
        fprintf(fp, "\t$(%s) -o $(BUILD_DIR)/$(PROJECT)_test $^ $(LDFLAGS) $(LDLIBS)\n",
                cc);
    } else {
        /* For libraries, link test objects with the library */
        fprintf(fp, "test: $(OUTPUT) $(TEST_OBJECTS)\n");
        fprintf(fp, "\t@mkdir -p $(BUILD_DIR)\n");
        if (strcmp(out_type, "shared") == 0) {
            fprintf(fp, "\t$(%s) -o $(BUILD_DIR)/$(PROJECT)_test $(TEST_OBJECTS) "
                        "-L$(BUILD_DIR) -l$(TARGET) $(LDFLAGS) $(LDLIBS)\n", cc);
        } else {
            fprintf(fp, "\t$(%s) -o $(BUILD_DIR)/$(PROJECT)_test $(TEST_OBJECTS) "
                        "$(OUTPUT) $(LDFLAGS) $(LDLIBS)\n", cc);
        }
    }
    fprintf(fp, "\t$(BUILD_DIR)/$(PROJECT)_test\n\n");

    /* ---- Install ---- */
    fprintf(fp, "# Install\n");
    fprintf(fp, "PREFIX   ?= /usr/local\n");
    if (strcmp(out_type, "executable") == 0) {
        fprintf(fp, "install: $(OUTPUT)\n");
        fprintf(fp, "\tinstall -d $(PREFIX)/bin\n");
        fprintf(fp, "\tinstall -m 755 $(OUTPUT) $(PREFIX)/bin/\n");
    } else if (strcmp(out_type, "header-only") == 0) {
        fprintf(fp, "install:\n");
        fprintf(fp, "\tinstall -d $(PREFIX)/include\n");
        fprintf(fp, "\tcp -r $(HDR_DIR)/* $(PREFIX)/include/\n");
    } else {
        fprintf(fp, "install: $(OUTPUT)\n");
        fprintf(fp, "\tinstall -d $(PREFIX)/lib $(PREFIX)/include\n");
        fprintf(fp, "\tinstall -m 644 $(OUTPUT) $(PREFIX)/lib/\n");
        fprintf(fp, "\tcp -r $(HDR_DIR)/* $(PREFIX)/include/\n");
    }
    fprintf(fp, "\n");

    /* ---- Clean ---- */
    fprintf(fp, "# Clean\n");
    fprintf(fp, "clean:\n");
    fprintf(fp, "\trm -rf $(BUILD_DIR)\n");

    fclose(fp);

    if (result) {
        result->code = NOW_OK;
        snprintf(result->message, sizeof(result->message),
                 "wrote %s", outpath);
    }
    return 0;
}

/* ---- export:meson ---- */

/* Map now optimization to meson optimization_level */
static const char *meson_opt_level(const char *opt) {
    if (!opt) return "0";
    if (strcmp(opt, "none") == 0)  return "0";
    if (strcmp(opt, "debug") == 0) return "g";
    if (strcmp(opt, "size") == 0)  return "s";
    if (strcmp(opt, "speed") == 0) return "2";
    if (strcmp(opt, "lto") == 0)   return "2";
    return "0";
}

/* Map now C std to meson c_std */
static const char *meson_c_std(const char *std_str) {
    if (!std_str) return "c11";
    if (strcmp(std_str, "c89") == 0 || strcmp(std_str, "c90") == 0) return "c89";
    if (strcmp(std_str, "c99") == 0) return "c99";
    if (strcmp(std_str, "c11") == 0) return "c11";
    if (strcmp(std_str, "c17") == 0 || strcmp(std_str, "c18") == 0) return "c17";
    if (strcmp(std_str, "c23") == 0) return "c2x";
    return "c11";
}

/* Map now C++ std to meson cpp_std */
static const char *meson_cxx_std(const char *std_str) {
    if (!std_str) return "c++17";
    if (strcmp(std_str, "c++11") == 0) return "c++11";
    if (strcmp(std_str, "c++14") == 0) return "c++14";
    if (strcmp(std_str, "c++17") == 0) return "c++17";
    if (strcmp(std_str, "c++20") == 0) return "c++20";
    if (strcmp(std_str, "c++23") == 0) return "c++23";
    return "c++17";
}

NOW_API int now_export_meson(const NowProject *project, const char *basedir,
                               const char *outpath, NowResult *result) {
    if (!project || !outpath) {
        if (result) {
            result->code = NOW_ERR_SCHEMA;
            snprintf(result->message, sizeof(result->message),
                     "export:meson: project and outpath required");
        }
        return -1;
    }

    FILE *fp = fopen(outpath, "w");
    if (!fp) {
        if (result) {
            result->code = NOW_ERR_IO;
            snprintf(result->message, sizeof(result->message),
                     "export:meson: cannot open %s", outpath);
        }
        return -1;
    }

    const char *pname = project->artifact ? project->artifact : "myproject";
    const char *pver  = project->version  ? project->version  : "0.1.0";
    int cxx = has_cxx(project);
    const char *lang = cxx ? "cpp" : "c";
    const char *out_type = project->output.type ? project->output.type : "executable";

    /* ---- project() ---- */
    fprintf(fp, "# Generated by now export:meson — do not edit\n\n");
    fprintf(fp, "project('%s', '%s',\n", pname, cxx ? "cpp" : "c");
    fprintf(fp, "  version : '%s',\n", pver);
    if (project->license)
        fprintf(fp, "  license : '%s',\n", project->license);
    fprintf(fp, "  default_options : [\n");
    if (cxx)
        fprintf(fp, "    '%s_std=%s',\n", lang, meson_cxx_std(project->std));
    else
        fprintf(fp, "    '%s_std=%s',\n", lang, meson_c_std(project->std));
    fprintf(fp, "    'optimization=%s',\n", meson_opt_level(
                project->compile.opt ? project->compile.opt : NULL));
    if (project->compile.opt && strcmp(project->compile.opt, "lto") == 0)
        fprintf(fp, "    'b_lto=true',\n");
    fprintf(fp, "  ]\n");
    fprintf(fp, ")\n\n");

    /* ---- Sources ---- */
    const char *src_dir = project->sources.dir ? project->sources.dir : "src/main/c";
    const char *hdr_dir = project->sources.headers ? project->sources.headers : "src/main/h";

    /* Collect source patterns */
    fprintf(fp, "src = files(\n");
    fprintf(fp, "  run_command('find', '%s', '-name', '*.c'", src_dir);
    if (cxx)
        fprintf(fp, ", '-o', '-name', '*.cpp', '-o', '-name', '*.cxx', '-o', '-name', '*.cc'");
    fprintf(fp, ",\n    check : true).stdout().strip().split('\\n'),\n");
    fprintf(fp, ")\n\n");

    /* ---- Include directories ---- */
    fprintf(fp, "inc = include_directories('%s'", hdr_dir);
    if (project->sources.private_headers)
        fprintf(fp, ", '%s'", project->sources.private_headers);
    for (size_t i = 0; i < project->compile.includes.count; i++)
        fprintf(fp, ", '%s'", project->compile.includes.items[i]);
    fprintf(fp, ")\n\n");

    /* ---- Compile args ---- */
    int has_args = (project->compile.warnings.count > 0 ||
                    project->compile.defines.count > 0 ||
                    project->compile.flags.count > 0);
    if (has_args) {
        fprintf(fp, "%s_args = [\n", lang);
        for (size_t i = 0; i < project->compile.warnings.count; i++)
            fprintf(fp, "  '-%s',\n", project->compile.warnings.items[i]);
        for (size_t i = 0; i < project->compile.defines.count; i++)
            fprintf(fp, "  '-D%s',\n", project->compile.defines.items[i]);
        for (size_t i = 0; i < project->compile.flags.count; i++)
            fprintf(fp, "  '%s',\n", project->compile.flags.items[i]);
        fprintf(fp, "]\n\n");
    }

    /* ---- Link args ---- */
    int has_link = (project->link.flags.count > 0 || project->link.libs.count > 0 ||
                    project->link.libdirs.count > 0);
    if (has_link) {
        fprintf(fp, "link_args = [\n");
        for (size_t i = 0; i < project->link.flags.count; i++)
            fprintf(fp, "  '%s',\n", project->link.flags.items[i]);
        for (size_t i = 0; i < project->link.libdirs.count; i++)
            fprintf(fp, "  '-L%s',\n", project->link.libdirs.items[i]);
        for (size_t i = 0; i < project->link.libs.count; i++)
            fprintf(fp, "  '-l%s',\n", project->link.libs.items[i]);
        fprintf(fp, "]\n\n");
    }

    /* ---- Target ---- */
    const char *out_name = project->output.name ? project->output.name : pname;

    if (strcmp(out_type, "executable") == 0) {
        fprintf(fp, "%s = executable('%s', src,\n", out_name, out_name);
    } else if (strcmp(out_type, "static") == 0) {
        fprintf(fp, "%s = static_library('%s', src,\n", out_name, out_name);
    } else if (strcmp(out_type, "shared") == 0) {
        fprintf(fp, "%s = shared_library('%s', src,\n", out_name, out_name);
    } else if (strcmp(out_type, "header-only") == 0) {
        /* Header-only: declare_dependency with include dirs only */
        fprintf(fp, "%s_dep = declare_dependency(\n", out_name);
        fprintf(fp, "  include_directories : inc,\n");
        fprintf(fp, ")\n\n");
        goto meson_deps_comment;
    } else {
        fprintf(fp, "%s = executable('%s', src,\n", out_name, out_name);
    }

    fprintf(fp, "  include_directories : inc,\n");
    if (has_args)
        fprintf(fp, "  %s_args : %s_args,\n", lang, lang);
    if (has_link)
        fprintf(fp, "  link_args : link_args,\n");
    fprintf(fp, "  install : true,\n");
    fprintf(fp, ")\n\n");

meson_deps_comment:
    /* ---- Dependencies comment ---- */
    if (project->deps.count > 0) {
        fprintf(fp, "# Dependencies (add via dependency() or subproject()):\n");
        for (size_t i = 0; i < project->deps.count; i++) {
            const char *scope = project->deps.items[i].scope
                                ? project->deps.items[i].scope : "compile";
            fprintf(fp, "#   %s [%s]\n", project->deps.items[i].id, scope);
        }
        fprintf(fp, "\n");
    }

    /* ---- Test target ---- */
    if (strcmp(out_type, "header-only") != 0) {
        const char *test_dir = project->tests.dir ? project->tests.dir : "src/test/c";
        fprintf(fp, "# Tests\n");
        fprintf(fp, "test_src = files(\n");
        fprintf(fp, "  run_command('find', '%s', '-name', '*.c'", test_dir);
        if (cxx)
            fprintf(fp, ", '-o', '-name', '*.cpp'");
        fprintf(fp, ",\n    check : true).stdout().strip().split('\\n'),\n");
        fprintf(fp, ")\n\n");

        if (strcmp(out_type, "executable") == 0) {
            fprintf(fp, "test_exe = executable('%s_test', test_src,\n", pname);
            fprintf(fp, "  include_directories : inc,\n");
            if (has_args)
                fprintf(fp, "  %s_args : %s_args,\n", lang, lang);
            fprintf(fp, ")\n");
        } else {
            fprintf(fp, "test_exe = executable('%s_test', test_src,\n", pname);
            fprintf(fp, "  include_directories : inc,\n");
            fprintf(fp, "  link_with : %s,\n", out_name);
            if (has_args)
                fprintf(fp, "  %s_args : %s_args,\n", lang, lang);
            fprintf(fp, ")\n");
        }
        fprintf(fp, "test('%s_test', test_exe)\n\n", pname);

        /* ---- Install headers ---- */
        fprintf(fp, "install_subdir('%s', install_dir : "
                    "get_option('includedir'))\n", hdr_dir);
    }

    fclose(fp);

    if (result) {
        result->code = NOW_OK;
        snprintf(result->message, sizeof(result->message),
                 "wrote %s", outpath);
    }
    return 0;
}

/* ---- export:bazel ---- */

NOW_API int now_export_bazel(const NowProject *project, const char *basedir,
                               const char *outpath, NowResult *result) {
    if (!project || !outpath) {
        if (result) {
            result->code = NOW_ERR_SCHEMA;
            snprintf(result->message, sizeof(result->message),
                     "export:bazel: project and outpath required");
        }
        return -1;
    }

    FILE *fp = fopen(outpath, "w");
    if (!fp) {
        if (result) {
            result->code = NOW_ERR_IO;
            snprintf(result->message, sizeof(result->message),
                     "export:bazel: cannot open %s", outpath);
        }
        return -1;
    }

    const char *pname = project->artifact ? project->artifact : "myproject";
    int cxx = has_cxx(project);
    const char *out_type = project->output.type ? project->output.type : "executable";
    const char *out_name = project->output.name ? project->output.name : pname;
    const char *src_dir = project->sources.dir ? project->sources.dir : "src/main/c";
    const char *hdr_dir = project->sources.headers ? project->sources.headers : "src/main/h";
    const char *test_dir = project->tests.dir ? project->tests.dir : "src/test/c";

    /* ---- Header ---- */
    fprintf(fp, "# Generated by now export:bazel — do not edit\n\n");
    fprintf(fp, "load(\"@rules_cc//cc:defs.bzl\", \"cc_binary\", \"cc_library\", \"cc_test\")\n\n");
    fprintf(fp, "package(default_visibility = [\"//visibility:public\"])\n\n");

    /* ---- COPTS ---- */
    int has_copts = (project->compile.warnings.count > 0 ||
                     project->compile.defines.count > 0 ||
                     project->compile.flags.count > 0 ||
                     project->std != NULL ||
                     (project->compile.opt && strcmp(project->compile.opt, "none") != 0));
    if (has_copts) {
        fprintf(fp, "COPTS = [\n");
        /* Standard */
        if (project->std) {
            fprintf(fp, "    \"-std=%s\",\n", project->std);
        }
        /* Optimization */
        if (project->compile.opt) {
            const char *oflag = cmake_opt_flags(project->compile.opt);
            if (oflag)
                fprintf(fp, "    \"%s\",\n", oflag);
        }
        for (size_t i = 0; i < project->compile.warnings.count; i++)
            fprintf(fp, "    \"-%s\",\n", project->compile.warnings.items[i]);
        for (size_t i = 0; i < project->compile.defines.count; i++)
            fprintf(fp, "    \"-D%s\",\n", project->compile.defines.items[i]);
        for (size_t i = 0; i < project->compile.flags.count; i++)
            fprintf(fp, "    \"%s\",\n", project->compile.flags.items[i]);
        fprintf(fp, "]\n\n");
    }

    /* ---- LINKOPTS ---- */
    int has_linkopts = (project->link.flags.count > 0 || project->link.libs.count > 0 ||
                        project->link.libdirs.count > 0);
    if (has_linkopts) {
        fprintf(fp, "LINKOPTS = [\n");
        for (size_t i = 0; i < project->link.flags.count; i++)
            fprintf(fp, "    \"%s\",\n", project->link.flags.items[i]);
        for (size_t i = 0; i < project->link.libdirs.count; i++)
            fprintf(fp, "    \"-L%s\",\n", project->link.libdirs.items[i]);
        for (size_t i = 0; i < project->link.libs.count; i++)
            fprintf(fp, "    \"-l%s\",\n", project->link.libs.items[i]);
        fprintf(fp, "]\n\n");
    }

    /* ---- Main target ---- */
    if (strcmp(out_type, "executable") == 0) {
        fprintf(fp, "cc_binary(\n");
        fprintf(fp, "    name = \"%s\",\n", out_name);
    } else if (strcmp(out_type, "header-only") == 0) {
        fprintf(fp, "cc_library(\n");
        fprintf(fp, "    name = \"%s\",\n", out_name);
    } else {
        /* static or shared → cc_library */
        fprintf(fp, "cc_library(\n");
        fprintf(fp, "    name = \"%s\",\n", out_name);
    }

    /* srcs */
    if (strcmp(out_type, "header-only") != 0) {
        fprintf(fp, "    srcs = glob([\"%s/**/*.c\"", src_dir);
        if (cxx)
            fprintf(fp, ", \"%s/**/*.cpp\", \"%s/**/*.cc\", \"%s/**/*.cxx\"",
                    src_dir, src_dir, src_dir);
        fprintf(fp, "]),\n");
    }

    /* hdrs */
    fprintf(fp, "    hdrs = glob([\"%s/**/*.h\"", hdr_dir);
    if (cxx)
        fprintf(fp, ", \"%s/**/*.hpp\"", hdr_dir);
    fprintf(fp, "]),\n");

    /* includes + strip_include_prefix */
    fprintf(fp, "    includes = [\"%s\"],\n", hdr_dir);
    fprintf(fp, "    strip_include_prefix = \"%s\",\n", hdr_dir);

    /* copts + linkopts */
    if (has_copts)
        fprintf(fp, "    copts = COPTS,\n");
    if (has_linkopts && strcmp(out_type, "header-only") != 0)
        fprintf(fp, "    linkopts = LINKOPTS,\n");

    /* linkstatic for static libs */
    if (strcmp(out_type, "static") == 0)
        fprintf(fp, "    linkstatic = True,\n");

    fprintf(fp, ")\n\n");

    /* ---- Dependencies comment ---- */
    if (project->deps.count > 0) {
        fprintf(fp, "# Dependencies (add via deps attribute):\n");
        for (size_t i = 0; i < project->deps.count; i++) {
            const char *scope = project->deps.items[i].scope
                                ? project->deps.items[i].scope : "compile";
            fprintf(fp, "#   %s [%s]\n", project->deps.items[i].id, scope);
        }
        fprintf(fp, "\n");
    }

    /* ---- Test target ---- */
    fprintf(fp, "cc_test(\n");
    fprintf(fp, "    name = \"%s_test\",\n", pname);
    fprintf(fp, "    srcs = glob([\"%s/**/*.c\"", test_dir);
    if (cxx)
        fprintf(fp, ", \"%s/**/*.cpp\"", test_dir);
    fprintf(fp, "]),\n");
    if (strcmp(out_type, "executable") == 0) {
        /* For executables, compile test with the source files */
        fprintf(fp, "    hdrs = glob([\"%s/**/*.h\"", hdr_dir);
        if (cxx)
            fprintf(fp, ", \"%s/**/*.hpp\"", hdr_dir);
        fprintf(fp, "]),\n");
        fprintf(fp, "    includes = [\"%s\"],\n", hdr_dir);
    } else {
        fprintf(fp, "    deps = [\":%s\"],\n", out_name);
    }
    if (has_copts)
        fprintf(fp, "    copts = COPTS,\n");
    fprintf(fp, ")\n");

    fclose(fp);

    if (result) {
        result->code = NOW_OK;
        snprintf(result->message, sizeof(result->message),
                 "wrote %s", outpath);
    }
    return 0;
}
