/*
 * now_maven.c — Maven import/export
 *
 * export:maven  — NowProject → pom.xml
 * import:maven  — pom.xml → NowProject → now.pasta
 */
#include "now_export.h"
#include "now_pom.h"
#include "now_fs.h"

#include "pasta.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

/* ================================================================
 * XML escape helper — emit text safe for XML element content
 * ================================================================ */
static void xml_escape(FILE *fp, const char *s) {
    if (!s) return;
    for (; *s; s++) {
        switch (*s) {
            case '&':  fputs("&amp;",  fp); break;
            case '<':  fputs("&lt;",   fp); break;
            case '>':  fputs("&gt;",   fp); break;
            case '"':  fputs("&quot;", fp); break;
            default:   fputc(*s, fp);       break;
        }
    }
}

/* Write a simple <tag>value</tag> element */
static void xml_elem(FILE *fp, int indent, const char *tag, const char *val) {
    if (!val) return;
    fprintf(fp, "%*s<%s>", indent, "", tag);
    xml_escape(fp, val);
    fprintf(fp, "</%s>\n", tag);
}

/* Split a "group:artifact:version" coordinate string.
 * Returns pointers into a malloc'd buffer (caller frees buf_out). */
static int split_gav(const char *id, char **buf_out,
                     const char **g, const char **a, const char **v) {
    if (!id) return -1;
    char *buf = strdup(id);
    if (!buf) return -1;

    char *p1 = strchr(buf, ':');
    if (!p1) { free(buf); return -1; }
    *p1++ = '\0';

    char *p2 = strchr(p1, ':');
    if (!p2) { free(buf); return -1; }
    *p2++ = '\0';

    *buf_out = buf;
    *g = buf;
    *a = p1;
    *v = p2;
    return 0;
}

/* ================================================================
 * export:maven  — generate pom.xml from NowProject
 * ================================================================ */

NOW_API int now_export_maven(const NowProject *project, const char *basedir,
                               const char *outpath, NowResult *result) {
    if (!project || !outpath) {
        if (result) {
            result->code = NOW_ERR_SCHEMA;
            snprintf(result->message, sizeof(result->message),
                     "export:maven: project and outpath required");
        }
        return -1;
    }

    FILE *fp = fopen(outpath, "w");
    if (!fp) {
        if (result) {
            result->code = NOW_ERR_IO;
            snprintf(result->message, sizeof(result->message),
                     "export:maven: cannot write %s", outpath);
        }
        return -1;
    }

    const char *group    = project->group    ? project->group    : "com.example";
    const char *artifact = project->artifact ? project->artifact : "project";
    const char *version  = project->version  ? project->version  : "0.1.0";

    /* ---- XML header ---- */
    fprintf(fp, "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
    fprintf(fp, "<!--\n");
    fprintf(fp, "  Generated by now %s — do not edit.\n", now_version());
    fprintf(fp, "  Regenerate with: now export:maven\n");
    fprintf(fp, "  Source: now.pasta\n");
    fprintf(fp, "-->\n");
    fprintf(fp, "<project xmlns=\"http://maven.apache.org/POM/4.0.0\"\n");
    fprintf(fp, "         xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n");
    fprintf(fp, "         xsi:schemaLocation=\"http://maven.apache.org/POM/4.0.0\n");
    fprintf(fp, "                             http://maven.apache.org/xsd/maven-4.0.0.xsd\">\n");
    fprintf(fp, "    <modelVersion>4.0.0</modelVersion>\n\n");

    /* ---- GAV coordinates ---- */
    xml_elem(fp, 4, "groupId",    group);
    xml_elem(fp, 4, "artifactId", artifact);
    xml_elem(fp, 4, "version",    version);

    /* Packaging */
    const char *out_type = project->output.type;
    if (out_type && strcmp(out_type, "executable") == 0)
        xml_elem(fp, 4, "packaging", "jar");
    else
        xml_elem(fp, 4, "packaging", "jar");

    fprintf(fp, "\n");

    /* ---- Project metadata ---- */
    if (project->name)
        xml_elem(fp, 4, "name", project->name);
    if (project->description)
        xml_elem(fp, 4, "description", project->description);
    if (project->url)
        xml_elem(fp, 4, "url", project->url);

    if (project->license) {
        fprintf(fp, "\n    <licenses>\n");
        fprintf(fp, "        <license>\n");
        xml_elem(fp, 12, "name", project->license);
        fprintf(fp, "        </license>\n");
        fprintf(fp, "    </licenses>\n");
    }

    fprintf(fp, "\n");

    /* ---- Properties ---- */
    const char *std = project->compile.std ? project->compile.std : project->std;
    const char *encoding = project->java.encoding ? project->java.encoding : "UTF-8";

    fprintf(fp, "    <properties>\n");
    xml_elem(fp, 8, "project.build.sourceEncoding", encoding);
    if (std)
        xml_elem(fp, 8, "maven.compiler.release", std);
    fprintf(fp, "    </properties>\n\n");

    /* ---- Dependencies ---- */
    if (project->deps.count > 0) {
        fprintf(fp, "    <dependencies>\n");
        for (size_t i = 0; i < project->deps.count; i++) {
            const NowDep *d = &project->deps.items[i];
            char *buf;
            const char *g, *a, *v;
            if (split_gav(d->id, &buf, &g, &a, &v) == 0) {
                fprintf(fp, "        <dependency>\n");
                xml_elem(fp, 12, "groupId",    g);
                xml_elem(fp, 12, "artifactId", a);

                /* Convert now version ranges to Maven:
                 * ^1.0.0 → [1.0.0,2.0.0)  (but for simplicity, emit as-is) */
                xml_elem(fp, 12, "version", v);

                if (d->scope && strcmp(d->scope, "compile") != 0)
                    xml_elem(fp, 12, "scope", d->scope);
                if (d->optional)
                    fprintf(fp, "            <optional>true</optional>\n");

                /* Exclusions */
                if (d->exclude.count > 0) {
                    fprintf(fp, "            <exclusions>\n");
                    for (size_t j = 0; j < d->exclude.count; j++) {
                        char *ebuf;
                        const char *eg, *ea, *ev;
                        if (split_gav(d->exclude.items[j], &ebuf, &eg, &ea, &ev) == 0) {
                            fprintf(fp, "                <exclusion>\n");
                            xml_elem(fp, 20, "groupId",    eg);
                            xml_elem(fp, 20, "artifactId", ea);
                            fprintf(fp, "                </exclusion>\n");
                            free(ebuf);
                        }
                    }
                    fprintf(fp, "            </exclusions>\n");
                }

                fprintf(fp, "        </dependency>\n");
                free(buf);
            }
        }
        fprintf(fp, "    </dependencies>\n\n");
    }

    /* ---- Repositories ---- */
    if (project->repos.count > 0) {
        fprintf(fp, "    <repositories>\n");
        for (size_t i = 0; i < project->repos.count; i++) {
            const NowRepo *r = &project->repos.items[i];
            fprintf(fp, "        <repository>\n");
            if (r->id)
                xml_elem(fp, 12, "id", r->id);
            else {
                char id_buf[32];
                snprintf(id_buf, sizeof(id_buf), "repo-%zu", i);
                xml_elem(fp, 12, "id", id_buf);
            }
            xml_elem(fp, 12, "url", r->url);
            fprintf(fp, "        </repository>\n");
        }
        fprintf(fp, "    </repositories>\n\n");
    }

    /* ---- Build configuration ---- */
    int need_build = (project->java.main_class != NULL) ||
                     (project->compile.flags.count > 0) ||
                     (project->sources.dir != NULL);

    if (need_build) {
        fprintf(fp, "    <build>\n");

        /* Source directory override */
        if (project->sources.dir)
            xml_elem(fp, 8, "sourceDirectory", project->sources.dir);
        if (project->tests.dir)
            xml_elem(fp, 8, "testSourceDirectory", project->tests.dir);

        fprintf(fp, "        <plugins>\n");

        /* maven-compiler-plugin */
        if (project->compile.flags.count > 0) {
            fprintf(fp, "            <plugin>\n");
            xml_elem(fp, 16, "groupId",    "org.apache.maven.plugins");
            xml_elem(fp, 16, "artifactId", "maven-compiler-plugin");
            xml_elem(fp, 16, "version",    "3.13.0");
            fprintf(fp, "                <configuration>\n");
            if (project->compile.flags.count > 0) {
                fprintf(fp, "                    <compilerArgs>\n");
                for (size_t i = 0; i < project->compile.flags.count; i++)
                    xml_elem(fp, 24, "arg", project->compile.flags.items[i]);
                fprintf(fp, "                    </compilerArgs>\n");
            }
            fprintf(fp, "                </configuration>\n");
            fprintf(fp, "            </plugin>\n");
        }

        /* maven-jar-plugin for executable (main class) */
        if (project->java.main_class) {
            fprintf(fp, "            <plugin>\n");
            xml_elem(fp, 16, "groupId",    "org.apache.maven.plugins");
            xml_elem(fp, 16, "artifactId", "maven-jar-plugin");
            xml_elem(fp, 16, "version",    "3.4.2");
            fprintf(fp, "                <configuration>\n");
            fprintf(fp, "                    <archive>\n");
            fprintf(fp, "                        <manifest>\n");
            xml_elem(fp, 28, "mainClass", project->java.main_class);
            fprintf(fp, "                        </manifest>\n");
            fprintf(fp, "                    </archive>\n");
            fprintf(fp, "                </configuration>\n");
            fprintf(fp, "            </plugin>\n");
        }

        fprintf(fp, "        </plugins>\n");
        fprintf(fp, "    </build>\n\n");
    }

    fprintf(fp, "</project>\n");
    fclose(fp);

    if (result) {
        result->code = NOW_OK;
        snprintf(result->message, sizeof(result->message),
                 "wrote %s", outpath);
    }
    return 0;
}


/* ================================================================
 * Minimal XML parser for pom.xml import
 *
 * A simple SAX-like state machine that tracks element paths and
 * accumulates text content. Only handles the subset of XML used
 * in Maven POM files (no attributes needed for data, no CDATA).
 * ================================================================ */

#define XML_MAX_DEPTH  32
#define XML_TAG_SIZE   128
#define XML_TEXT_SIZE  1024

typedef struct {
    /* Tag stack */
    char tags[XML_MAX_DEPTH][XML_TAG_SIZE];
    int  depth;

    /* Text accumulator between open/close tags */
    char text[XML_TEXT_SIZE];
    int  text_len;

    /* Output project */
    NowProject *project;

    /* Current dependency being assembled */
    int  in_dep;
    char dep_group[256];
    char dep_artifact[256];
    char dep_version[256];
    char dep_scope[64];
    int  dep_optional;

    /* Current repository */
    int  in_repo;
    char repo_id[256];
    char repo_url[512];

    /* Properties map (simple key=value for ${...} substitution) */
    int    in_properties;
    char   prop_key[128];   /* tag name under <properties> */
    char  *props_keys[64];
    char  *props_vals[64];
    int    prop_count;

    /* Build flags */
    int  in_compiler_args;
    int  in_manifest;
} XmlCtx;

/* Build the current element path as "project/dependencies/dependency/..." */
static void xml_path(const XmlCtx *ctx, char *buf, size_t bufsize) {
    buf[0] = '\0';
    for (int i = 0; i < ctx->depth; i++) {
        if (i > 0) strncat(buf, "/", bufsize - strlen(buf) - 1);
        strncat(buf, ctx->tags[i], bufsize - strlen(buf) - 1);
    }
}

/* Perform ${property} substitution on a string */
static char *xml_subst_props(const XmlCtx *ctx, const char *val) {
    if (!val || !strchr(val, '$')) return strdup(val);

    size_t cap = strlen(val) * 2 + 64;
    char *out = malloc(cap);
    if (!out) return strdup(val);

    size_t olen = 0;
    const char *p = val;
    while (*p) {
        if (p[0] == '$' && p[1] == '{') {
            const char *end = strchr(p + 2, '}');
            if (end) {
                size_t klen = (size_t)(end - p - 2);
                char key[128];
                if (klen < sizeof(key)) {
                    memcpy(key, p + 2, klen);
                    key[klen] = '\0';

                    /* Check project.version etc. */
                    const char *rep = NULL;
                    if (strcmp(key, "project.version") == 0)
                        rep = ctx->project->version;
                    else if (strcmp(key, "project.groupId") == 0)
                        rep = ctx->project->group;
                    else if (strcmp(key, "project.artifactId") == 0)
                        rep = ctx->project->artifact;
                    else {
                        for (int i = 0; i < ctx->prop_count; i++) {
                            if (strcmp(ctx->props_keys[i], key) == 0) {
                                rep = ctx->props_vals[i];
                                break;
                            }
                        }
                    }

                    if (rep) {
                        size_t rlen = strlen(rep);
                        while (olen + rlen + 1 > cap) { cap *= 2; out = realloc(out, cap); }
                        memcpy(out + olen, rep, rlen);
                        olen += rlen;
                        p = end + 1;
                        continue;
                    }
                }
            }
        }
        if (olen + 2 > cap) { cap *= 2; out = realloc(out, cap); }
        out[olen++] = *p++;
    }
    out[olen] = '\0';
    return out;
}

/* Called when a close tag is encountered — dispatch text to project fields */
static void xml_on_close(XmlCtx *ctx) {
    char path[512];
    xml_path(ctx, path, sizeof(path));

    /* Trim whitespace from text */
    char *text = ctx->text;
    while (*text && isspace((unsigned char)*text)) text++;
    char *end = text + strlen(text);
    while (end > text && isspace((unsigned char)end[-1])) *--end = '\0';

    if (*text == '\0') goto done;

    /* Substitute properties */
    char *val = xml_subst_props(ctx, text);
    if (!val) goto done;

    /* ---- Identity ---- */
    if (strcmp(path, "project/groupId") == 0) {
        free(ctx->project->group);
        ctx->project->group = val; val = NULL;
    } else if (strcmp(path, "project/artifactId") == 0) {
        free(ctx->project->artifact);
        ctx->project->artifact = val; val = NULL;
    } else if (strcmp(path, "project/version") == 0) {
        free(ctx->project->version);
        ctx->project->version = val; val = NULL;
    } else if (strcmp(path, "project/name") == 0) {
        free(ctx->project->name);
        ctx->project->name = val; val = NULL;
    } else if (strcmp(path, "project/description") == 0) {
        free(ctx->project->description);
        ctx->project->description = val; val = NULL;
    } else if (strcmp(path, "project/url") == 0) {
        free(ctx->project->url);
        ctx->project->url = val; val = NULL;
    } else if (strcmp(path, "project/packaging") == 0) {
        /* jar → executable if main_class present, otherwise jar */
        free(ctx->project->output.type);
        ctx->project->output.type = val; val = NULL;
    } else if (strcmp(path, "project/licenses/license/name") == 0) {
        free(ctx->project->license);
        ctx->project->license = val; val = NULL;
    }

    /* ---- Properties ---- */
    else if (ctx->in_properties && ctx->depth >= 3) {
        /* path is "project/properties/<key>" */
        const char *pkey = ctx->tags[ctx->depth - 1];
        if (strcmp(pkey, "maven.compiler.release") == 0 ||
            strcmp(pkey, "maven.compiler.source") == 0) {
            free(ctx->project->std);
            ctx->project->std = val; val = NULL;
        } else if (strcmp(pkey, "project.build.sourceEncoding") == 0) {
            free(ctx->project->java.encoding);
            ctx->project->java.encoding = val; val = NULL;
        }
        /* Store in props table for substitution */
        if (ctx->prop_count < 64) {
            ctx->props_keys[ctx->prop_count] = strdup(pkey);
            ctx->props_vals[ctx->prop_count] = strdup(text);
            ctx->prop_count++;
        }
    }

    /* ---- Dependencies ---- */
    else if (ctx->in_dep) {
        if (strcmp(path, "project/dependencies/dependency/groupId") == 0)
            snprintf(ctx->dep_group, sizeof(ctx->dep_group), "%s", val);
        else if (strcmp(path, "project/dependencies/dependency/artifactId") == 0)
            snprintf(ctx->dep_artifact, sizeof(ctx->dep_artifact), "%s", val);
        else if (strcmp(path, "project/dependencies/dependency/version") == 0)
            snprintf(ctx->dep_version, sizeof(ctx->dep_version), "%s", val);
        else if (strcmp(path, "project/dependencies/dependency/scope") == 0)
            snprintf(ctx->dep_scope, sizeof(ctx->dep_scope), "%s", val);
        else if (strcmp(path, "project/dependencies/dependency/optional") == 0)
            ctx->dep_optional = (strcmp(val, "true") == 0);
    }

    /* ---- Repositories ---- */
    else if (ctx->in_repo) {
        if (strcmp(path, "project/repositories/repository/id") == 0)
            snprintf(ctx->repo_id, sizeof(ctx->repo_id), "%s", val);
        else if (strcmp(path, "project/repositories/repository/url") == 0)
            snprintf(ctx->repo_url, sizeof(ctx->repo_url), "%s", val);
    }

    /* ---- Build config ---- */
    else if (ctx->in_compiler_args) {
        /* Each <arg> under compilerArgs */
        if (strstr(path, "/compilerArgs/arg"))
            now_strarray_push(&ctx->project->compile.flags, val);
    }
    else if (ctx->in_manifest) {
        if (strstr(path, "/mainClass")) {
            free(ctx->project->java.main_class);
            ctx->project->java.main_class = val; val = NULL;
        }
    }

    /* ---- Source directories ---- */
    else if (strcmp(path, "project/build/sourceDirectory") == 0) {
        free(ctx->project->sources.dir);
        ctx->project->sources.dir = val; val = NULL;
    }
    else if (strcmp(path, "project/build/testSourceDirectory") == 0) {
        free(ctx->project->tests.dir);
        ctx->project->tests.dir = val; val = NULL;
    }

    free(val);

done:
    /* Handle end-of-dependency */
    if (strcmp(path, "project/dependencies/dependency") == 0 && ctx->in_dep) {
        ctx->in_dep = 0;
        if (ctx->dep_group[0] && ctx->dep_artifact[0]) {
            int idx = now_deparray_push(&ctx->project->deps);
            if (idx >= 0) {
                NowDep *d = &ctx->project->deps.items[idx];
                /* Build "group:artifact:version" id */
                size_t id_len = strlen(ctx->dep_group) + strlen(ctx->dep_artifact) +
                                strlen(ctx->dep_version) + 3;
                d->id = malloc(id_len);
                if (d->id)
                    snprintf(d->id, id_len, "%s:%s:%s",
                             ctx->dep_group, ctx->dep_artifact, ctx->dep_version);
                if (ctx->dep_scope[0])
                    d->scope = strdup(ctx->dep_scope);
                d->optional = ctx->dep_optional;
            }
        }
    }

    /* Handle end-of-repository */
    if (strcmp(path, "project/repositories/repository") == 0 && ctx->in_repo) {
        ctx->in_repo = 0;
        if (ctx->repo_url[0]) {
            int idx = now_repoarray_push(&ctx->project->repos);
            if (idx >= 0) {
                NowRepo *r = &ctx->project->repos.items[idx];
                r->url = strdup(ctx->repo_url);
                if (ctx->repo_id[0])
                    r->id = strdup(ctx->repo_id);
            }
        }
    }
}

/* Called when an open tag is encountered */
static void xml_on_open(XmlCtx *ctx) {
    char path[512];
    xml_path(ctx, path, sizeof(path));

    if (strcmp(path, "project/dependencies/dependency") == 0) {
        ctx->in_dep = 1;
        ctx->dep_group[0] = ctx->dep_artifact[0] = ctx->dep_version[0] = '\0';
        ctx->dep_scope[0] = '\0';
        ctx->dep_optional = 0;
    } else if (strcmp(path, "project/repositories/repository") == 0) {
        ctx->in_repo = 1;
        ctx->repo_id[0] = ctx->repo_url[0] = '\0';
    } else if (strcmp(path, "project/properties") == 0) {
        ctx->in_properties = 1;
    } else if (strstr(path, "/compilerArgs")) {
        ctx->in_compiler_args = 1;
    } else if (strstr(path, "/manifest")) {
        ctx->in_manifest = 1;
    }
}

/* Minimal XML parser — drives the XmlCtx state machine */
static int xml_parse(XmlCtx *ctx, const char *xml, size_t len) {
    const char *p = xml;
    const char *end = xml + len;

    while (p < end) {
        if (*p == '<') {
            p++;
            if (p >= end) break;

            /* Skip processing instructions <?...?> */
            if (*p == '?') {
                while (p < end && !(p[0] == '?' && p + 1 < end && p[1] == '>')) p++;
                if (p + 1 < end) p += 2;
                continue;
            }

            /* Skip comments <!--...--> */
            if (p + 2 < end && p[0] == '!' && p[1] == '-' && p[2] == '-') {
                p += 3;
                while (p + 2 < end && !(p[0] == '-' && p[1] == '-' && p[2] == '>')) p++;
                if (p + 2 < end) p += 3;
                continue;
            }

            /* Skip <!DOCTYPE...> */
            if (*p == '!') {
                while (p < end && *p != '>') p++;
                if (p < end) p++;
                continue;
            }

            /* Closing tag </tag> */
            if (*p == '/') {
                p++;
                /* Just skip to '>' — we rely on the depth stack */
                while (p < end && *p != '>') p++;
                if (p < end) p++;

                /* Dispatch text to handler */
                ctx->text[ctx->text_len] = '\0';
                xml_on_close(ctx);

                /* Pop depth */
                if (ctx->depth > 0) {
                    /* Check flag clearing */
                    char path[512];
                    xml_path(ctx, path, sizeof(path));
                    if (strcmp(path, "project/properties") == 0)
                        ctx->in_properties = 0;
                    if (strstr(path, "/compilerArgs"))
                        ctx->in_compiler_args = 0;
                    if (strstr(path, "/manifest"))
                        ctx->in_manifest = 0;

                    ctx->depth--;
                }
                ctx->text_len = 0;
                continue;
            }

            /* Opening tag — extract name */
            const char *name_start = p;
            while (p < end && *p != '>' && *p != ' ' && *p != '/' && *p != '\t' && *p != '\n')
                p++;
            size_t name_len = (size_t)(p - name_start);
            if (name_len >= XML_TAG_SIZE) name_len = XML_TAG_SIZE - 1;

            /* Skip attributes, detect self-closing (only '/>' counts) */
            int self_closing = 0;
            int in_attr_val = 0;
            while (p < end && *p != '>') {
                if (*p == '"') in_attr_val = !in_attr_val;
                if (!in_attr_val && *p == '/' && p + 1 < end && p[1] == '>')
                    self_closing = 1;
                p++;
            }
            if (p < end) p++;  /* skip '>' */

            /* Push tag */
            if (ctx->depth < XML_MAX_DEPTH) {
                memcpy(ctx->tags[ctx->depth], name_start, name_len);
                ctx->tags[ctx->depth][name_len] = '\0';
                ctx->depth++;
                ctx->text_len = 0;

                xml_on_open(ctx);

                if (self_closing) {
                    ctx->text[0] = '\0';
                    xml_on_close(ctx);
                    ctx->depth--;
                }
            }
        } else {
            /* Text content — accumulate */
            if (ctx->text_len < XML_TEXT_SIZE - 1)
                ctx->text[ctx->text_len++] = *p;
            p++;
        }
    }

    return 0;
}

/* ================================================================
 * import:maven  — parse pom.xml → NowProject
 * ================================================================ */

NOW_API NowProject *now_import_maven(const char *pom_path, NowResult *result) {
    if (!pom_path) {
        if (result) {
            result->code = NOW_ERR_IO;
            snprintf(result->message, sizeof(result->message),
                     "import:maven: no pom.xml path");
        }
        return NULL;
    }

    /* Read file */
    FILE *fp = fopen(pom_path, "rb");
    if (!fp) {
        if (result) {
            result->code = NOW_ERR_IO;
            snprintf(result->message, sizeof(result->message),
                     "import:maven: cannot open %s", pom_path);
        }
        return NULL;
    }

    fseek(fp, 0, SEEK_END);
    long len = ftell(fp);
    fseek(fp, 0, SEEK_SET);

    char *xml = malloc((size_t)len + 1);
    if (!xml) {
        fclose(fp);
        if (result) {
            result->code = NOW_ERR_ALLOC;
            snprintf(result->message, sizeof(result->message), "out of memory");
        }
        return NULL;
    }
    fread(xml, 1, (size_t)len, fp);
    xml[len] = '\0';
    fclose(fp);

    /* Set up parse context */
    XmlCtx ctx;
    memset(&ctx, 0, sizeof(ctx));
    ctx.project = now_project_new();
    if (!ctx.project) {
        free(xml);
        if (result) {
            result->code = NOW_ERR_ALLOC;
            snprintf(result->message, sizeof(result->message), "out of memory");
        }
        return NULL;
    }

    /* Set default Java lang */
    now_strarray_push(&ctx.project->langs, "java");

    xml_parse(&ctx, xml, (size_t)len);
    free(xml);

    /* Free props table */
    for (int i = 0; i < ctx.prop_count; i++) {
        free(ctx.props_keys[i]);
        free(ctx.props_vals[i]);
    }

    /* Apply defaults for Java */
    if (!ctx.project->sources.dir)
        ctx.project->sources.dir = strdup("src/main/java");
    if (!ctx.project->tests.dir)
        ctx.project->tests.dir = strdup("src/test/java");
    if (!ctx.project->output.type)
        ctx.project->output.type = strdup("jar");
    if (!ctx.project->output.name && ctx.project->artifact)
        ctx.project->output.name = strdup(ctx.project->artifact);

    if (result) {
        result->code = NOW_OK;
        snprintf(result->message, sizeof(result->message),
                 "imported %s", pom_path);
    }
    return ctx.project;
}


/* ================================================================
 * import:maven write — NowProject → now.pasta
 * ================================================================ */

NOW_API int now_import_maven_write(const NowProject *project,
                                     const char *outpath, NowResult *result) {
    if (!project || !outpath) {
        if (result) {
            result->code = NOW_ERR_SCHEMA;
            snprintf(result->message, sizeof(result->message),
                     "import:maven: project and outpath required");
        }
        return -1;
    }

    FILE *fp = fopen(outpath, "w");
    if (!fp) {
        if (result) {
            result->code = NOW_ERR_IO;
            snprintf(result->message, sizeof(result->message),
                     "import:maven: cannot write %s", outpath);
        }
        return -1;
    }

    /* Build the Pasta map as text.
     * Print comma before each field except the first. */
    fprintf(fp, "{\n");
    int need_comma = 0;

    #define COMMA() do { if (need_comma) fprintf(fp, ",\n"); need_comma = 1; } while (0)

    if (project->group)       { COMMA(); fprintf(fp, "  group: \"%s\"",       project->group); }
    if (project->artifact)    { COMMA(); fprintf(fp, "  artifact: \"%s\"",    project->artifact); }
    if (project->version)     { COMMA(); fprintf(fp, "  version: \"%s\"",     project->version); }
    if (project->name)        { COMMA(); fprintf(fp, "  name: \"%s\"",        project->name); }
    if (project->description) { COMMA(); fprintf(fp, "  description: \"%s\"", project->description); }
    if (project->url)         { COMMA(); fprintf(fp, "  url: \"%s\"",         project->url); }
    if (project->license)     { COMMA(); fprintf(fp, "  license: \"%s\"",     project->license); }

    /* Languages */
    COMMA(); fprintf(fp, "  langs: [\"java\"]");

    /* Standard */
    if (project->std) { COMMA(); fprintf(fp, "  std: \"%s\"", project->std); }

    /* Output */
    COMMA();
    fprintf(fp, "  output: { type: \"%s\"",
            project->output.type ? project->output.type : "jar");
    if (project->output.name)
        fprintf(fp, ", name: \"%s\"", project->output.name);
    fprintf(fp, " }");

    /* Java section */
    if (project->java.main_class || project->java.encoding) {
        COMMA();
        fprintf(fp, "  java: {");
        int first = 1;
        if (project->java.main_class) {
            fprintf(fp, " main_class: \"%s\"", project->java.main_class);
            first = 0;
        }
        if (project->java.encoding) {
            if (!first) fprintf(fp, ",");
            fprintf(fp, " encoding: \"%s\"", project->java.encoding);
        }
        fprintf(fp, " }");
    }

    /* Sources */
    if (project->sources.dir) { COMMA(); fprintf(fp, "  sources: { dir: \"%s\" }", project->sources.dir); }
    if (project->tests.dir)   { COMMA(); fprintf(fp, "  tests: { dir: \"%s\" }",   project->tests.dir); }

    /* Compile flags */
    if (project->compile.flags.count > 0) {
        COMMA();
        fprintf(fp, "  compile: { flags: [");
        for (size_t i = 0; i < project->compile.flags.count; i++) {
            if (i > 0) fprintf(fp, ", ");
            fprintf(fp, "\"%s\"", project->compile.flags.items[i]);
        }
        fprintf(fp, "] }");
    }

    /* Dependencies */
    if (project->deps.count > 0) {
        COMMA();
        fprintf(fp, "  deps: [\n");
        for (size_t i = 0; i < project->deps.count; i++) {
            const NowDep *d = &project->deps.items[i];
            fprintf(fp, "    { id: \"%s\"", d->id);
            if (d->scope && strcmp(d->scope, "compile") != 0)
                fprintf(fp, ", scope: \"%s\"", d->scope);
            if (d->optional)
                fprintf(fp, ", optional: true");
            fprintf(fp, " }");
            if (i + 1 < project->deps.count) fprintf(fp, ",");
            fprintf(fp, "\n");
        }
        fprintf(fp, "  ]");
    }

    /* Repositories */
    if (project->repos.count > 0) {
        COMMA();
        fprintf(fp, "  repos: [\n");
        for (size_t i = 0; i < project->repos.count; i++) {
            const NowRepo *r = &project->repos.items[i];
            fprintf(fp, "    { url: \"%s\"", r->url);
            if (r->id)
                fprintf(fp, ", id: \"%s\"", r->id);
            fprintf(fp, " }");
            if (i + 1 < project->repos.count) fprintf(fp, ",");
            fprintf(fp, "\n");
        }
        fprintf(fp, "  ]");
    }

    #undef COMMA

    fprintf(fp, "\n}\n");
    fclose(fp);

    if (result) {
        result->code = NOW_OK;
        snprintf(result->message, sizeof(result->message),
                 "wrote %s", outpath);
    }
    return 0;
}
