/* now_export_make.c — Makefile exporter */
#include "now_export.h"
#include "now_export_common.h"
#include "now_pom.h"
#include "now_fs.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static const char *make_opt_flag(const char *opt) {
    if (!opt) return "-O0";
    if (strcmp(opt, "none") == 0)  return "-O0";
    if (strcmp(opt, "debug") == 0) return "-Og";
    if (strcmp(opt, "size") == 0)  return "-Os";
    if (strcmp(opt, "speed") == 0) return "-O2";
    if (strcmp(opt, "lto") == 0)   return "-O2 -flto";
    return "-O0";
}

NOW_API int now_export_make(const NowProject *project, const char *basedir,
                              const char *outpath, NowResult *result) {
    if (!project || !outpath) {
        if (result) {
            result->code = NOW_ERR_SCHEMA;
            snprintf(result->message, sizeof(result->message),
                     "export:make: project and outpath required");
        }
        return -1;
    }

    FILE *fp = fopen(outpath, "w");
    if (!fp) {
        if (result) {
            result->code = NOW_ERR_IO;
            snprintf(result->message, sizeof(result->message),
                     "export:make: cannot write %s", outpath);
        }
        return -1;
    }

    const char *artifact = project->artifact ? project->artifact : "project";
    const char *version  = project->version  ? project->version  : "0.1.0";
    const char *out_type = project->output.type ? project->output.type : "executable";
    const char *out_name = project->output.name ? project->output.name : artifact;
    int use_cxx = export_has_cxx(project);

    /* Source directory */
    const char *src_dir = project->sources.dir;
    if (!src_dir) src_dir = use_cxx ? "src/main/cpp" : "src/main/c";

    /* Header directory */
    const char *hdr_dir = project->sources.headers;
    if (!hdr_dir) hdr_dir = use_cxx ? "src/main/hpp" : "src/main/h";

    /* Test directory */
    const char *test_dir = project->tests.dir;
    if (!test_dir) test_dir = use_cxx ? "src/test/cpp" : "src/test/c";

    /* Compiler */
    const char *cc = use_cxx ? "CXX" : "CC";
    const char *cc_default = use_cxx ? "g++" : "gcc";

    /* ---- Header ---- */
    fprintf(fp, "# Generated by now %s — do not edit.\n", now_version());
    fprintf(fp, "# Regenerate with: now export:make\n");
    fprintf(fp, "# Source: now.pasta\n");
    fprintf(fp, "#\n");
    if (project->name)
        fprintf(fp, "# %s", project->name);
    if (project->description)
        fprintf(fp, " — %s", project->description);
    if (project->name || project->description)
        fprintf(fp, "\n");
    fprintf(fp, "\n");

    /* ---- Variables ---- */
    fprintf(fp, "# Project\n");
    fprintf(fp, "PROJECT  := %s\n", artifact);
    fprintf(fp, "VERSION  := %s\n", version);
    fprintf(fp, "TARGET   := %s\n", out_name);
    fprintf(fp, "\n");

    fprintf(fp, "# Toolchain\n");
    fprintf(fp, "%s       ?= %s\n", cc, cc_default);
    fprintf(fp, "AR       ?= ar\n");
    fprintf(fp, "\n");

    /* Directories */
    fprintf(fp, "# Directories\n");
    fprintf(fp, "SRC_DIR  := %s\n", src_dir);
    fprintf(fp, "HDR_DIR  := %s\n", hdr_dir);
    fprintf(fp, "TEST_DIR := %s\n", test_dir);
    fprintf(fp, "BUILD_DIR := target\n");
    fprintf(fp, "OBJ_DIR  := $(BUILD_DIR)/obj\n");
    fprintf(fp, "\n");

    /* Source discovery */
    fprintf(fp, "# Sources\n");
    if (use_cxx) {
        fprintf(fp, "SOURCES  := $(wildcard $(SRC_DIR)/*.c) "
                    "$(wildcard $(SRC_DIR)/*.cpp) "
                    "$(wildcard $(SRC_DIR)/*.cxx) "
                    "$(wildcard $(SRC_DIR)/*.cc)\n");
    } else {
        fprintf(fp, "SOURCES  := $(wildcard $(SRC_DIR)/*.c)\n");
    }
    fprintf(fp, "OBJECTS  := $(patsubst $(SRC_DIR)/%%, $(OBJ_DIR)/%%.o, "
                "$(SOURCES))\n");
    fprintf(fp, "\n");

    /* Test sources */
    fprintf(fp, "# Test sources\n");
    if (use_cxx) {
        fprintf(fp, "TEST_SOURCES := $(wildcard $(TEST_DIR)/*.c) "
                    "$(wildcard $(TEST_DIR)/*.cpp) "
                    "$(wildcard $(TEST_DIR)/*.cxx) "
                    "$(wildcard $(TEST_DIR)/*.cc)\n");
    } else {
        fprintf(fp, "TEST_SOURCES := $(wildcard $(TEST_DIR)/*.c)\n");
    }
    fprintf(fp, "TEST_OBJECTS := $(patsubst $(TEST_DIR)/%%, "
                "$(OBJ_DIR)/test_%%.o, $(TEST_SOURCES))\n");
    fprintf(fp, "\n");

    /* Flags */
    fprintf(fp, "# Flags\n");

    /* Standard */
    if (project->std) {
        fprintf(fp, "CFLAGS   += -std=%s\n", project->std);
    } else {
        fprintf(fp, "CFLAGS   += %s\n",
                use_cxx ? "-std=c++17" : "-std=c11");
    }

    /* Include paths */
    fprintf(fp, "CFLAGS   += -I$(HDR_DIR) -I$(SRC_DIR)\n");
    for (size_t i = 0; i < project->compile.includes.count; i++)
        fprintf(fp, "CFLAGS   += -I%s\n", project->compile.includes.items[i]);

    /* Warnings */
    for (size_t i = 0; i < project->compile.warnings.count; i++)
        fprintf(fp, "CFLAGS   += -%s\n", project->compile.warnings.items[i]);

    /* Optimization */
    fprintf(fp, "CFLAGS   += %s\n", make_opt_flag(project->compile.opt));

    /* Defines */
    for (size_t i = 0; i < project->compile.defines.count; i++)
        fprintf(fp, "CFLAGS   += -D%s\n", project->compile.defines.items[i]);

    /* Raw compile flags */
    for (size_t i = 0; i < project->compile.flags.count; i++)
        fprintf(fp, "CFLAGS   += %s\n", project->compile.flags.items[i]);

    fprintf(fp, "\n");

    /* Linker flags */
    fprintf(fp, "LDFLAGS  :=\n");
    for (size_t i = 0; i < project->link.libdirs.count; i++)
        fprintf(fp, "LDFLAGS  += -L%s\n", project->link.libdirs.items[i]);
    for (size_t i = 0; i < project->link.flags.count; i++)
        fprintf(fp, "LDFLAGS  += %s\n", project->link.flags.items[i]);

    fprintf(fp, "LDLIBS   :=\n");
    for (size_t i = 0; i < project->link.libs.count; i++)
        fprintf(fp, "LDLIBS   += -l%s\n", project->link.libs.items[i]);
    fprintf(fp, "\n");

    /* Output-type-specific settings */
    if (strcmp(out_type, "shared") == 0) {
        fprintf(fp, "# Shared library\n");
        fprintf(fp, "CFLAGS   += -fPIC\n");
        fprintf(fp, "OUTPUT   := $(BUILD_DIR)/lib$(TARGET).so\n");
    } else if (strcmp(out_type, "static") == 0) {
        fprintf(fp, "# Static library\n");
        fprintf(fp, "OUTPUT   := $(BUILD_DIR)/lib$(TARGET).a\n");
    } else {
        fprintf(fp, "# Executable\n");
        fprintf(fp, "OUTPUT   := $(BUILD_DIR)/$(TARGET)\n");
    }
    fprintf(fp, "\n");

    /* Dependencies (as comments) */
    if (project->deps.count > 0) {
        fprintf(fp, "# Dependencies from now.pasta (resolve manually):\n");
        for (size_t i = 0; i < project->deps.count; i++) {
            const NowDep *d = &project->deps.items[i];
            fprintf(fp, "#   %s", d->id);
            if (d->scope && strcmp(d->scope, "compile") != 0)
                fprintf(fp, "  (scope: %s)", d->scope);
            if (d->optional)
                fprintf(fp, "  (optional)");
            fprintf(fp, "\n");
        }
        fprintf(fp, "\n");
    }

    /* ---- Phony targets ---- */
    fprintf(fp, "# ---- Targets ----\n\n");
    fprintf(fp, ".PHONY: all clean test install\n\n");
    fprintf(fp, "all: $(OUTPUT)\n\n");

    /* ---- Build rules ---- */
    if (strcmp(out_type, "shared") == 0) {
        fprintf(fp, "$(OUTPUT): $(OBJECTS)\n");
        fprintf(fp, "\t@mkdir -p $(dir $@)\n");
        fprintf(fp, "\t$(%s) -shared -o $@ $^ $(LDFLAGS) $(LDLIBS)\n\n", cc);
    } else if (strcmp(out_type, "static") == 0) {
        fprintf(fp, "$(OUTPUT): $(OBJECTS)\n");
        fprintf(fp, "\t@mkdir -p $(dir $@)\n");
        fprintf(fp, "\t$(AR) rcs $@ $^\n\n");
    } else {
        fprintf(fp, "$(OUTPUT): $(OBJECTS)\n");
        fprintf(fp, "\t@mkdir -p $(dir $@)\n");
        fprintf(fp, "\t$(%s) -o $@ $^ $(LDFLAGS) $(LDLIBS)\n\n", cc);
    }

    /* Object compilation rule */
    fprintf(fp, "$(OBJ_DIR)/%%.c.o: $(SRC_DIR)/%%.c\n");
    fprintf(fp, "\t@mkdir -p $(dir $@)\n");
    fprintf(fp, "\t$(%s) $(CFLAGS) -c -o $@ $<\n\n", cc);

    if (use_cxx) {
        fprintf(fp, "$(OBJ_DIR)/%%.cpp.o: $(SRC_DIR)/%%.cpp\n");
        fprintf(fp, "\t@mkdir -p $(dir $@)\n");
        fprintf(fp, "\t$(%s) $(CFLAGS) -c -o $@ $<\n\n", cc);

        fprintf(fp, "$(OBJ_DIR)/%%.cxx.o: $(SRC_DIR)/%%.cxx\n");
        fprintf(fp, "\t@mkdir -p $(dir $@)\n");
        fprintf(fp, "\t$(%s) $(CFLAGS) -c -o $@ $<\n\n", cc);

        fprintf(fp, "$(OBJ_DIR)/%%.cc.o: $(SRC_DIR)/%%.cc\n");
        fprintf(fp, "\t@mkdir -p $(dir $@)\n");
        fprintf(fp, "\t$(%s) $(CFLAGS) -c -o $@ $<\n\n", cc);
    }

    /* ---- Test target ---- */
    fprintf(fp, "# Test\n");
    fprintf(fp, "$(OBJ_DIR)/test_%%.c.o: $(TEST_DIR)/%%.c\n");
    fprintf(fp, "\t@mkdir -p $(dir $@)\n");
    fprintf(fp, "\t$(%s) $(CFLAGS) -c -o $@ $<\n\n", cc);

    if (use_cxx) {
        fprintf(fp, "$(OBJ_DIR)/test_%%.cpp.o: $(TEST_DIR)/%%.cpp\n");
        fprintf(fp, "\t@mkdir -p $(dir $@)\n");
        fprintf(fp, "\t$(%s) $(CFLAGS) -c -o $@ $<\n\n", cc);
    }

    if (strcmp(out_type, "executable") == 0) {
        /* For executables, link test with all source objects (caller excludes main) */
        fprintf(fp, "test: $(TEST_OBJECTS) $(OBJECTS)\n");
        fprintf(fp, "\t@mkdir -p $(BUILD_DIR)\n");
        fprintf(fp, "\t$(%s) -o $(BUILD_DIR)/$(PROJECT)_test $^ $(LDFLAGS) $(LDLIBS)\n",
                cc);
    } else {
        /* For libraries, link test objects with the library */
        fprintf(fp, "test: $(OUTPUT) $(TEST_OBJECTS)\n");
        fprintf(fp, "\t@mkdir -p $(BUILD_DIR)\n");
        if (strcmp(out_type, "shared") == 0) {
            fprintf(fp, "\t$(%s) -o $(BUILD_DIR)/$(PROJECT)_test $(TEST_OBJECTS) "
                        "-L$(BUILD_DIR) -l$(TARGET) $(LDFLAGS) $(LDLIBS)\n", cc);
        } else {
            fprintf(fp, "\t$(%s) -o $(BUILD_DIR)/$(PROJECT)_test $(TEST_OBJECTS) "
                        "$(OUTPUT) $(LDFLAGS) $(LDLIBS)\n", cc);
        }
    }
    fprintf(fp, "\t$(BUILD_DIR)/$(PROJECT)_test\n\n");

    /* ---- Install ---- */
    fprintf(fp, "# Install\n");
    fprintf(fp, "PREFIX   ?= /usr/local\n");
    if (strcmp(out_type, "executable") == 0) {
        fprintf(fp, "install: $(OUTPUT)\n");
        fprintf(fp, "\tinstall -d $(PREFIX)/bin\n");
        fprintf(fp, "\tinstall -m 755 $(OUTPUT) $(PREFIX)/bin/\n");
    } else if (strcmp(out_type, "header-only") == 0) {
        fprintf(fp, "install:\n");
        fprintf(fp, "\tinstall -d $(PREFIX)/include\n");
        fprintf(fp, "\tcp -r $(HDR_DIR)/* $(PREFIX)/include/\n");
    } else {
        fprintf(fp, "install: $(OUTPUT)\n");
        fprintf(fp, "\tinstall -d $(PREFIX)/lib $(PREFIX)/include\n");
        fprintf(fp, "\tinstall -m 644 $(OUTPUT) $(PREFIX)/lib/\n");
        fprintf(fp, "\tcp -r $(HDR_DIR)/* $(PREFIX)/include/\n");
    }
    fprintf(fp, "\n");

    /* ---- Clean ---- */
    fprintf(fp, "# Clean\n");
    fprintf(fp, "clean:\n");
    fprintf(fp, "\trm -rf $(BUILD_DIR)\n");

    fclose(fp);

    if (result) {
        result->code = NOW_OK;
        snprintf(result->message, sizeof(result->message),
                 "wrote %s", outpath);
    }
    return 0;
}

/* ---- export:meson ---- */

/* Map now optimization to meson optimization_level */

/* Map now C std to meson c_std */

/* Map now C++ std to meson cpp_std */

