/* now_export_cmake.c — CMake exporter */
#include "now_export.h"
#include "now_export_common.h"
#include "now_pom.h"
#include "now_fs.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Source glob patterns for CMake file(GLOB_RECURSE ...) */
static const char *c_glob_patterns =
    "\"${CMAKE_SOURCE_DIR}/%s/*.c\"\n"
    "    \"${CMAKE_SOURCE_DIR}/%s/*.i\"";

static const char *cxx_glob_patterns =
    "\"${CMAKE_SOURCE_DIR}/%s/*.cpp\"\n"
    "    \"${CMAKE_SOURCE_DIR}/%s/*.cxx\"\n"
    "    \"${CMAKE_SOURCE_DIR}/%s/*.cc\"";
NOW_API int now_export_cmake(const NowProject *project, const char *basedir,
                              const char *outpath, NowResult *result) {
    if (!project || !outpath) {
        if (result) {
            result->code = NOW_ERR_SCHEMA;
            snprintf(result->message, sizeof(result->message),
                     "export:cmake: project and outpath required");
        }
        return -1;
    }

    FILE *fp = fopen(outpath, "w");
    if (!fp) {
        if (result) {
            result->code = NOW_ERR_IO;
            snprintf(result->message, sizeof(result->message),
                     "export:cmake: cannot write %s", outpath);
        }
        return -1;
    }

    const char *artifact = project->artifact ? project->artifact : "project";
    const char *version  = project->version  ? project->version  : "0.1.0";
    const char *out_type = project->output.type ? project->output.type : "executable";
    const char *out_name = project->output.name ? project->output.name : artifact;
    int use_cxx = export_has_cxx(project);

    /* Source directory (default: src/main/c or src/main/cpp) */
    const char *src_dir = project->sources.dir;
    if (!src_dir) src_dir = use_cxx ? "src/main/cpp" : "src/main/c";

    /* Header directory */
    const char *hdr_dir = project->sources.headers;
    if (!hdr_dir) hdr_dir = use_cxx ? "src/main/hpp" : "src/main/h";

    /* Test directory */
    const char *test_dir = project->tests.dir;
    if (!test_dir) test_dir = use_cxx ? "src/test/cpp" : "src/test/c";

    /* ---- Header ---- */
    fprintf(fp, "# Generated by now %s — do not edit.\n", now_version());
    fprintf(fp, "# Regenerate with: now export:cmake\n");
    fprintf(fp, "# Source: now.pasta\n");
    fprintf(fp, "#\n");
    if (project->name)
        fprintf(fp, "# %s", project->name);
    if (project->description)
        fprintf(fp, " — %s", project->description);
    if (project->name || project->description)
        fprintf(fp, "\n");
    fprintf(fp, "\n");

    /* ---- CMake preamble ---- */
    fprintf(fp, "cmake_minimum_required(VERSION 3.20)\n");

    /* Languages */
    fprintf(fp, "project(%s VERSION %s LANGUAGES", artifact, version);
    if (use_cxx) fprintf(fp, " CXX");
    fprintf(fp, " C)\n\n");

    /* Standards */
    if (use_cxx) {
        int cxx_ver = export_cxx_std(project->std);
        fprintf(fp, "set(CMAKE_CXX_STANDARD %d)\n", cxx_ver);
        fprintf(fp, "set(CMAKE_CXX_STANDARD_REQUIRED ON)\n");
    }
    int c_ver = export_c_std(project->std);
    fprintf(fp, "set(CMAKE_C_STANDARD %d)\n", c_ver);
    fprintf(fp, "set(CMAKE_C_STANDARD_REQUIRED ON)\n");
    fprintf(fp, "\n");

    /* ---- Source discovery ---- */
    fprintf(fp, "# Source files\n");
    fprintf(fp, "file(GLOB_RECURSE SOURCES\n");
    fprintf(fp, "    ");
    fprintf(fp, c_glob_patterns, src_dir, src_dir);
    fprintf(fp, "\n");
    if (use_cxx) {
        fprintf(fp, "    ");
        fprintf(fp, cxx_glob_patterns, src_dir, src_dir, src_dir);
        fprintf(fp, "\n");
    }
    fprintf(fp, ")\n\n");

    /* ---- Target definition ---- */
    if (strcmp(out_type, "executable") == 0) {
        fprintf(fp, "add_executable(%s ${SOURCES})\n", out_name);
    } else if (strcmp(out_type, "static") == 0) {
        fprintf(fp, "add_library(%s STATIC ${SOURCES})\n", out_name);
    } else if (strcmp(out_type, "shared") == 0) {
        fprintf(fp, "add_library(%s SHARED ${SOURCES})\n", out_name);
    } else if (strcmp(out_type, "header-only") == 0) {
        fprintf(fp, "add_library(%s INTERFACE)\n", out_name);
    } else {
        fprintf(fp, "add_executable(%s ${SOURCES})\n", out_name);
    }
    fprintf(fp, "\n");

    /* ---- Include directories ---- */
    if (strcmp(out_type, "header-only") == 0) {
        fprintf(fp, "target_include_directories(%s INTERFACE\n", out_name);
        fprintf(fp, "    $<BUILD_INTERFACE:${CMAKE_SOURCE_DIR}/%s>\n", hdr_dir);
        fprintf(fp, "    $<INSTALL_INTERFACE:include>\n");
        fprintf(fp, ")\n\n");
    } else {
        fprintf(fp, "target_include_directories(%s\n", out_name);
        fprintf(fp, "    PUBLIC  $<BUILD_INTERFACE:${CMAKE_SOURCE_DIR}/%s>\n", hdr_dir);
        fprintf(fp, "            $<INSTALL_INTERFACE:include>\n");
        fprintf(fp, "    PRIVATE ${CMAKE_SOURCE_DIR}/%s\n", src_dir);
        fprintf(fp, ")\n\n");

        /* Extra include paths from compile.includes */
        if (project->compile.includes.count > 0) {
            fprintf(fp, "target_include_directories(%s PRIVATE\n", out_name);
            for (size_t i = 0; i < project->compile.includes.count; i++)
                fprintf(fp, "    ${CMAKE_SOURCE_DIR}/%s\n",
                        project->compile.includes.items[i]);
            fprintf(fp, ")\n\n");
        }
    }

    /* ---- Compile options ---- */
    if (project->compile.warnings.count > 0 ||
        project->compile.flags.count > 0 ||
        project->compile.opt) {
        fprintf(fp, "target_compile_options(%s PRIVATE\n", out_name);

        /* Warnings */
        for (size_t i = 0; i < project->compile.warnings.count; i++)
            fprintf(fp, "    -%s\n", project->compile.warnings.items[i]);

        /* Optimization */
        const char *opt = export_opt_flags(project->compile.opt);
        if (opt) fprintf(fp, "    %s\n", opt);

        /* Raw flags */
        for (size_t i = 0; i < project->compile.flags.count; i++)
            fprintf(fp, "    %s\n", project->compile.flags.items[i]);

        fprintf(fp, ")\n\n");
    }

    /* ---- Compile definitions ---- */
    if (project->compile.defines.count > 0) {
        fprintf(fp, "target_compile_definitions(%s PRIVATE\n", out_name);
        for (size_t i = 0; i < project->compile.defines.count; i++)
            fprintf(fp, "    %s\n", project->compile.defines.items[i]);
        fprintf(fp, ")\n\n");
    }

    /* ---- Link options ---- */
    if (project->link.flags.count > 0) {
        fprintf(fp, "target_link_options(%s PRIVATE\n", out_name);
        for (size_t i = 0; i < project->link.flags.count; i++)
            fprintf(fp, "    %s\n", project->link.flags.items[i]);
        fprintf(fp, ")\n\n");
    }

    /* ---- Link libraries ---- */
    if (project->link.libs.count > 0 || project->link.libdirs.count > 0) {
        if (project->link.libdirs.count > 0) {
            fprintf(fp, "target_link_directories(%s PRIVATE\n", out_name);
            for (size_t i = 0; i < project->link.libdirs.count; i++)
                fprintf(fp, "    %s\n", project->link.libdirs.items[i]);
            fprintf(fp, ")\n\n");
        }
        if (project->link.libs.count > 0) {
            fprintf(fp, "target_link_libraries(%s PRIVATE\n", out_name);
            for (size_t i = 0; i < project->link.libs.count; i++)
                fprintf(fp, "    %s\n", project->link.libs.items[i]);
            fprintf(fp, ")\n\n");
        }
    }

    /* ---- Dependencies (as comments — cannot auto-resolve) ---- */
    if (project->deps.count > 0) {
        fprintf(fp, "# Dependencies from now.pasta (resolve manually or use FetchContent):\n");
        for (size_t i = 0; i < project->deps.count; i++) {
            const NowDep *d = &project->deps.items[i];
            fprintf(fp, "#   %s", d->id);
            if (d->scope && strcmp(d->scope, "compile") != 0)
                fprintf(fp, "  (scope: %s)", d->scope);
            if (d->optional)
                fprintf(fp, "  (optional)");
            fprintf(fp, "\n");
        }
        fprintf(fp, "#\n");
        fprintf(fp, "# Example using FetchContent:\n");
        fprintf(fp, "# include(FetchContent)\n");
        fprintf(fp, "# FetchContent_Declare(dep_name URL <url>)\n");
        fprintf(fp, "# FetchContent_MakeAvailable(dep_name)\n");
        fprintf(fp, "# target_link_libraries(%s PRIVATE dep_name)\n", out_name);
        fprintf(fp, "\n");
    }

    /* ---- Test target ---- */
    fprintf(fp, "# Test target\n");
    fprintf(fp, "option(%s_BUILD_TESTS \"Build test executable\" ON)\n", artifact);
    fprintf(fp, "if(%s_BUILD_TESTS)\n", artifact);
    fprintf(fp, "    file(GLOB_RECURSE TEST_SOURCES\n");
    fprintf(fp, "        ");
    fprintf(fp, c_glob_patterns, test_dir, test_dir);
    fprintf(fp, "\n");
    if (use_cxx) {
        fprintf(fp, "        ");
        fprintf(fp, cxx_glob_patterns, test_dir, test_dir, test_dir);
        fprintf(fp, "\n");
    }
    fprintf(fp, "    )\n");
    fprintf(fp, "    if(TEST_SOURCES)\n");
    if (strcmp(out_type, "executable") == 0) {
        /* For executables, test links against sources directly (minus main) */
        fprintf(fp, "        add_executable(%s_test ${TEST_SOURCES} ${SOURCES})\n",
                artifact);
    } else {
        /* For libraries, test links against the library */
        fprintf(fp, "        add_executable(%s_test ${TEST_SOURCES})\n", artifact);
        fprintf(fp, "        target_link_libraries(%s_test PRIVATE %s)\n",
                artifact, out_name);
    }
    fprintf(fp, "        target_include_directories(%s_test PRIVATE\n", artifact);
    fprintf(fp, "            ${CMAKE_SOURCE_DIR}/%s\n", hdr_dir);
    fprintf(fp, "            ${CMAKE_SOURCE_DIR}/%s\n", src_dir);
    fprintf(fp, "        )\n");
    fprintf(fp, "    endif()\n");
    fprintf(fp, "endif()\n\n");

    /* ---- Install rules ---- */
    fprintf(fp, "# Install rules\n");
    fprintf(fp, "include(GNUInstallDirs)\n");
    if (strcmp(out_type, "header-only") == 0) {
        fprintf(fp, "install(DIRECTORY %s/ DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})\n",
                hdr_dir);
    } else {
        fprintf(fp, "install(TARGETS %s\n", out_name);
        fprintf(fp, "    RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}\n");
        fprintf(fp, "    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}\n");
        fprintf(fp, "    ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}\n");
        fprintf(fp, ")\n");
        fprintf(fp, "install(DIRECTORY %s/ DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})\n",
                hdr_dir);
    }
    fprintf(fp, "\n");

    fclose(fp);

    if (result) {
        result->code = NOW_OK;
        snprintf(result->message, sizeof(result->message),
                 "wrote %s", outpath);
    }
    return 0;
}

/* ---- export:make ---- */

/* Map now optimization level to GCC/Clang -O flag */

